In [1]:
import pandas as pd

In [83]:
df = pd.DataFrame({
    'Age': [25, 30, 28, None, 35],
    'Salary': [50000, None, 58000, 62000, 60000]
    })
df.isnull()

     Age  Salary
0  False   False
1  False    True
2  False   False
3   True   False
4  False   False

In [84]:
df.dropna()  # Removes rows with any missing values

    Age   Salary
0  25.0  50000.0
2  28.0  58000.0
4  35.0  60000.0

In [85]:
df

    Age   Salary
0  25.0  50000.0
1  30.0      NaN
2  28.0  58000.0
3   NaN  62000.0
4  35.0  60000.0

In [86]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

In [87]:
df

    Age   Salary
0  25.0  50000.0
1  30.0      NaN
2  28.0  58000.0
3  29.5  62000.0
4  35.0  60000.0

In [88]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
df_filled = imputer.fit_transform(df)
df_filled

array([[2.50e+01, 5.00e+04],
       [3.00e+01, 6.00e+04],
       [2.80e+01, 5.80e+04],
       [2.95e+01, 6.20e+04],
       [3.50e+01, 6.00e+04]])

In [82]:
# Update the original DataFrame with the imputed values
df[['Age', 'Salary']] = df_filled

# Display the final DataFrame with all replaced values
df

    Age   Salary
0  25.0  50000.0
1  30.0  60000.0
2  28.0  58000.0
3  29.5  62000.0
4  35.0  60000.0

In [16]:
# Convert the imputed NumPy array back to a DataFrame
df_filled = pd.DataFrame(df_filled, columns=df.columns)

# Display the imputed DataFrame
df_filled

    Age   Salary
0  25.0  50000.0
1  30.0  54000.0
2  28.0  58000.0
3  31.5  62000.0
4  35.0  60000.0

In [25]:
df = pd.DataFrame({
    'Age': [25, 30, 28, None, 35],
    'Gender': ['F', None, 'M', 'M', 'M']
    })
df

    Age Gender
0  25.0      F
1  30.0   None
2  28.0      M
3   NaN      M
4  35.0      M

In [28]:
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df

    Age Gender
0  25.0      F
1  30.0      M
2  28.0      M
3   NaN      M
4  35.0      M

In [29]:
import pandas as pd
import numpy as np

In [39]:
data = {
    'Name': ['Haris', 'Sam', 'Rick', 'Maggy', 'Daryl', 'Robita', 'Negan', np.nan],
    'Age': [28, np.nan, 35, 30, 40, np.nan, 45, 38],
    'Salary': [50000, 60000, np.nan, 55000, 70000, 80000, np.nan, 90000],
    'Department': ['HR', 'IT', 'Sales', np.nan, 'HR', 'Marketing', 'IT', 'Sales'],
    'Gender': ['Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male', np.nan]
}

# Create a DataFrame
df = pd.DataFrame(data)
df

     Name   Age   Salary Department  Gender
0   Haris  28.0  50000.0         HR    Male
1     Sam   NaN  60000.0         IT    Male
2    Rick  35.0      NaN      Sales    Male
3   Maggy  30.0  55000.0        NaN  Female
4   Daryl  40.0  70000.0         HR    Male
5  Robita   NaN  80000.0  Marketing  Female
6   Negan  45.0      NaN         IT    Male
7     NaN  38.0  90000.0      Sales     NaN

In [34]:
df.isnull().sum()

Name          1
Age           2
Salary        2
Department    1
Gender        1
dtype: int64

In [35]:
# Mean Imputation for 'Age' column
df['Age'].fillna(df['Age'].mean(), inplace=True)
df

     Name   Age   Salary Department  Gender
0   Haris  28.0  50000.0         HR    Male
1     Sam  36.0  60000.0         IT    Male
2    Rick  35.0      NaN      Sales    Male
3   Maggy  30.0  55000.0        NaN  Female
4   Daryl  40.0  70000.0         HR    Male
5  Robita  36.0  80000.0  Marketing  Female
6   Negan  45.0      NaN         IT    Male
7     NaN  38.0  90000.0      Sales     NaN

In [36]:
# Median Imputation for 'Salary' column
df['Salary'].fillna(df['Salary'].median(), inplace=True)
df

     Name   Age   Salary Department  Gender
0   Haris  28.0  50000.0         HR    Male
1     Sam  36.0  60000.0         IT    Male
2    Rick  35.0  65000.0      Sales    Male
3   Maggy  30.0  55000.0        NaN  Female
4   Daryl  40.0  70000.0         HR    Male
5  Robita  36.0  80000.0  Marketing  Female
6   Negan  45.0  65000.0         IT    Male
7     NaN  38.0  90000.0      Sales     NaN

In [37]:
# Mode Imputation for 'Department' column
df['Department'].fillna(df['Department'].mode()[0], inplace=True)
df

     Name   Age   Salary Department  Gender
0   Haris  28.0  50000.0         HR    Male
1     Sam  36.0  60000.0         IT    Male
2    Rick  35.0  65000.0      Sales    Male
3   Maggy  30.0  55000.0         HR  Female
4   Daryl  40.0  70000.0         HR    Male
5  Robita  36.0  80000.0  Marketing  Female
6   Negan  45.0  65000.0         IT    Male
7     NaN  38.0  90000.0      Sales     NaN

In [38]:
# Creating a new 'Unknown' category for missing values in 'Gender'
df['Gender'].fillna('Unknown', inplace=True)
df

     Name   Age   Salary Department   Gender
0   Haris  28.0  50000.0         HR     Male
1     Sam  36.0  60000.0         IT     Male
2    Rick  35.0  65000.0      Sales     Male
3   Maggy  30.0  55000.0         HR   Female
4   Daryl  40.0  70000.0         HR     Male
5  Robita  36.0  80000.0  Marketing   Female
6   Negan  45.0  65000.0         IT     Male
7     NaN  38.0  90000.0      Sales  Unknown

In [40]:
df

     Name   Age   Salary Department  Gender
0   Haris  28.0  50000.0         HR    Male
1     Sam   NaN  60000.0         IT    Male
2    Rick  35.0      NaN      Sales    Male
3   Maggy  30.0  55000.0        NaN  Female
4   Daryl  40.0  70000.0         HR    Male
5  Robita   NaN  80000.0  Marketing  Female
6   Negan  45.0      NaN         IT    Male
7     NaN  38.0  90000.0      Sales     NaN

In [72]:
from sklearn.impute import KNNImputer

# Using KNN Imputer to fill missing values
imputer = KNNImputer(n_neighbors=2)
df_imputed = pd.DataFrame(imputer.fit_transform(df[['Age', 'Salary']]), columns=['Age', 'Salary'])

df[['Age','Salary']] = df_imputed
df

    Age   Salary
0  28.0  50000.0
1  29.0  60000.0
2  35.0  83800.0
3  30.0  55000.0
4  40.0  70000.0
5  29.0  53400.0
6  45.0  85000.0
7  38.0  90000.0

In [44]:
df

     Name   Age   Salary Department  Gender
0   Haris  28.0  50000.0         HR    Male
1     Sam   NaN  60000.0         IT    Male
2    Rick  35.0      NaN      Sales    Male
3   Maggy  30.0  55000.0        NaN  Female
4   Daryl  40.0  70000.0         HR    Male
5  Robita   NaN  80000.0  Marketing  Female
6   Negan  45.0      NaN         IT    Male
7     NaN  38.0  90000.0      Sales     NaN

In [43]:
# Dropping rows with missing values in the 'Name' column
df_dropped = df.dropna(subset=['Name'])
df_dropped

     Name   Age   Salary Department  Gender
0   Haris  28.0  50000.0         HR    Male
1     Sam   NaN  60000.0         IT    Male
2    Rick  35.0      NaN      Sales    Male
3   Maggy  30.0  55000.0        NaN  Female
4   Daryl  40.0  70000.0         HR    Male
5  Robita   NaN  80000.0  Marketing  Female
6   Negan  45.0      NaN         IT    Male

In [62]:
data = {
    'Name': ['Haris', 'Sam', 'Rick', 'Maggy', 'Daryl', 'Robita', 'Negan', np.nan],
    'Age': [28, 29, 35, 30, 40, 29, 45, 38],
    'Salary': [50000, 60000, np.nan, 55000, 70000, np.nan, 85000, 90000],
    'Department': ['HR', 'IT', 'Sales', np.nan, 'HR', 'Marketing', 'IT', 'Sales'],
    'Gender': ['Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Male', np.nan]
}

# Create a DataFrame
df = pd.DataFrame(data)
df

     Name  Age   Salary Department  Gender
0   Haris   28  50000.0         HR    Male
1     Sam   29  60000.0         IT    Male
2    Rick   35      NaN      Sales    Male
3   Maggy   30  55000.0        NaN  Female
4   Daryl   40  70000.0         HR    Male
5  Robita   29      NaN  Marketing  Female
6   Negan   45  85000.0         IT    Male
7     NaN   38  90000.0      Sales     NaN

In [63]:
df.isnull().sum()

Name          1
Age           0
Salary        2
Department    1
Gender        1
dtype: int64

## Preprocessing

In [64]:
# Convert categorical variables using one-hot encoding
df_encoded = pd.get_dummies(df[['Department', 'Gender']], drop_first=True)

# Add the one-hot encoded columns back to the original DataFrame
df = pd.concat([df[['Age', 'Salary']], df_encoded], axis=1)

# Display the updated DataFrame
df

,Age,Salary,Department_IT,Department_Marketing,Department_Sales,Gender_Male
0,28,50000.0,0,0,0,1
1,29,60000.0,1,0,0,1
2,35,NaN,0,0,1,1
3,30,55000.0,0,0,0,0
4,40,70000.0,0,0,0,1
5,29,NaN,0,1,0,0
6,45,85000.0,1,0,0,1
7,38,90000.0,0,0,1,0

## Split Data into Training and Prediction Sets

In [65]:
# Split the dataset into training and prediction sets for 'Salary'
train_data = df[df['Salary'].notna()]  # Data where Salary is not missing
predict_data = df[df['Salary'].isna()]  # Data where Salary is missing

# Separate features and target variable
X_train = train_data.drop('Salary', axis=1)
y_train = train_data['Salary']

X_predict = predict_data.drop('Salary', axis=1)

## Train a Regression Model

In [66]:
from sklearn.linear_model import LinearRegression

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [68]:
# Predict the missing Salary values
predicted_salaries = model.predict(X_predict)
predicted_salaries

array([83800., 53400.])

In [69]:
# Assign the predicted salaries back to the DataFrame
df.loc[df['Salary'].isna(), 'Salary'] = predicted_salaries

# Display the DataFrame with filled Salary values
df

,Age,Salary,Department_IT,Department_Marketing,Department_Sales,Gender_Male
0,28,50000.0,0,0,0,1
1,29,60000.0,1,0,0,1
2,35,83800.0,0,0,1,1
3,30,55000.0,0,0,0,0
4,40,70000.0,0,0,0,1
5,29,53400.0,0,1,0,0
6,45,85000.0,1,0,0,1
7,38,90000.0,0,0,1,0

## Evaluating the result

In [71]:
# Check for missing values again
print(df.isnull().sum())

Age                     0
Salary                  0
Department_IT           0
Department_Marketing    0
Department_Sales        0
Gender_Male             0
dtype: int64