In [2]:
! pip install selenium

Requirement already satisfied: selenium in c:\users\aysha\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\aysha\anaconda3\lib\site-packages (from selenium) (2022.9.14)
Requirement already satisfied: trio~=0.17 in c:\users\aysha\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\aysha\anaconda3\lib\site-packages (from selenium) (1.26.11)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\aysha\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: sniffio in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: outcome in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.1)
Requirement already satisfied: idna in c:\users\aysha\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: wsproto>=0.14 in c:\users\aysha\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\aysha\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\aysha\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\aysha\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import re
import requests
from bs4 import BeautifulSoup
from selenium import webdriver

import time

In [6]:
URL = 'https://www.flipkart.com/search?q=phone&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.price_range.from%3D20000&p%5B%5D=facets.price_range.to%3DMax&page=1'
page = requests.get(URL)
page.status_code

200

In [7]:
page.content

b'<!doctype html><html lang="en"><head><link href="https://rukminim1.flixcart.com" rel="preconnect"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.905c37.css"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.914d0a.css"/><meta http-equiv="Content-type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta property="fb:page_id" content="102988293558"/><meta property="fb:admins" content="658873552,624500995,100000233612389"/><meta name="robots" content="noodp"/><link rel="shortcut icon" href="https:///www/promos/new/20150528-140547-favicon-retina.ico"/><link type="application/opensearchdescription+xml" rel="search" href="/osdd.xml?v=2"/><meta property="og:type" content="website"/><meta name="og_site_name" property="og:site_name" content="Flipkart.com"/><link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon" href="/apple-touch-icon-57x57.png"/><meta name="twitter:card" content="app"><meta name="twitter:site" content="@flipkart"><meta name="twitter:creator" content="@flipkart"><meta name="twitter:title" content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com"><meta name="twitter:description" content="Shop for electronics, apparels & more using our Flipkart app Free shipping & COD."><meta name="twitter:app:country" content="in"><meta name="al:ios:app_name" content="Flipkart"><meta name="al:ios:app_store_id" content="742044692"><meta name="twitter:app:name:iphone" content="Flipkart"><meta name="twitter:app:id:iphone" content="742044692"><meta name="twitter:app:url:iphone" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:ipad" content="Flipkart"><meta name="twitter:app:id:ipad" content="742044692"><meta name="twitter:app:url:ipad" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:googleplay" content="Flipkart"><meta name="twitter:app:id:googleplay" content="com.flipkart.android"><meta name="twitter:app:url:googleplay" content="http://dl.flipkart.com/dl/home?"><style>#container {\n\t\t\theight: 100%;\n\t\t}</style>  <link rel="stylesheet" href="///fk-cp-zion/css/Browse.chunk.eb4d21.css"/><title>Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta name="og_title" property="og:title" content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com"/><meta name="Keywords" content="Phone"/> <meta name="Description" content="Phone- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/><meta property="og:description" content="Phone- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/> <meta name="robots" content="noindex"/>   <meta name="msvalidate.01" content="F4EEB3A0AFFDD385992A06E6920C0AC3"/> <!--[if IE 9 ]>\n\t<script nonce="15151522127138223793">\n\t\twindow.browserVersion = \'IE9\';\n\t\tdocument.documentElement.className += \' ie9\';\n\t</script>\n\t<![endif]--><!--[if !IE]><!--><script nonce="15151522127138223793">if (/*@cc_on!@*/false) {\n\t\t\twindow.browserVersion = \'IE10\';\n\t\t\tdocument.documentElement.className += \' ie10\';\n\t\t}</script><!--<![endif]-->   <link href="https://www.flipkart.com/search?q&#x3D;phone&amp;otracker&#x3D;search&amp;otracker1&#x3D;search&amp;marketplace&#x3D;FLIPKART&amp;as-show&#x3D;on&amp;as&#x3D;off&amp;p%5B%5D&#x3D;facets.price_range.from%3D20000&amp;p%5B%5D&#x3D;facets.price_range.to%3DMax&amp;page&#x3D;2" id="next-page-link-tag" rel="next"><script nonce="15151522127138223793">!function(){if("PerformancePaintTiming" in window){var e=window.__perf={e:[]};e.o=new PerformanceObserver(function(n){e.e=e.e.concat(n.getEntries())});try{e.o.observe({entryTypes:["paint"]})}catch(e){}}}();\n\n\t\tif (requestAnimationFrame && performance && performance.mark) {\n\t\t\trequestAnimationFrame(function () {\n\t\t\t\twindow.first_paint = performance.now();\n\t\t\t\tperformance.mark("first_paint");\n\t\t\t});\n\t\t}\n\n        // web-vitals polyfill for FID\n        !function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);</script><script async src="https://www.googletagmanager.com/gtag/js?id=AW-594691041"></script><script nonce="15151522127138223793">window.dataLayer = window.dataLayer || [];\n\t\tfunction gtag(){dataLayer.push(arguments)};\n\t\tgtag(\'js\', new Date());</script></head><body><div id="container"><div><div class="_1kfTjk"><div class="_1rH5Jn"><div class="_1TmfNK"></div><div class="_2Xfa2_"><div class="_3_C9Hx"><div class="_3qX0zy"><a href="/"><img width="75" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/flipkart-plus_8d85f4.png" alt="Flipkart" title="Flipkart" class="_2xm1JU"/></a><a class="_21ljIi" href="/plus">Explore<!-- --> <span class="_2FVHGh">Plus</span><img width="10" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/plus_aef861.png"/></a></div></div><div class="_1cmsER"><form class="_2M8cLY header-form-search" action="/search" method="GET"><div class="col-12-12 _2oO9oE"><div class="_3OO5Xc"><input type="text" value="phone" class="_3704LK" title="Search for products, brands and more" name="q" autoComplete="off" placeholder="Search for products, brands and more"/></div><button class="L0Z3Pu" type="submit"><svg width="20" height="20" viewBox="0 0 17 18" class="" xmlns="http://www.w3.org/2000/svg"><g fill="#2874F1" fill-rule="evenodd"><path class="_34RNph" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203"></path><path class="_34RNph" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467"></path></g></svg></button><input type="hidden" name="otracker" value="search"/><input type="hidden" name="otracker1" value="search"/><input type="hidden" name="marketplace" value="FLIPKART"/><input type="hidden" name="as-show" value="off"/><input type="hidden" name="as" value="off"/></div><ul class="col-12-12 _1MRYA1"></ul></form></div><div class="go_DOp _2errNR"><div class="_28p97w"><div class="_1psGvi _3BvnxG"><div><a class="_1_3w1N" href="/account/login?ret=/search%3Fq%3Dphone%26otracker%3Dsearch%26otracker1%3Dsearch%26marketplace%3DFLIPKART%26as-show%3Don%26as%3Doff%26p%255B%255D%3Dfacets.price_range.from%253D20000%26p%255B%255D%3Dfacets.price_range.to%253DMax%26page%3D1">Login</a></div></div></div></div><div class="go_DOp"><a href="https://seller.flipkart.com/sell-online/?utm_source=fkwebsite&amp;utm_medium=websitedirect" class="_3-PJz-"><span>Become a Seller</span></a></div><div class="go_DOp"><div class="_28p97w"><div class="_1psGvi _3BvnxG"><div><div class="exehdJ"> <!-- -->More<!-- --> </div></div></div><svg width="4.7" height="8" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="zZ3yfL"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="_2gTTdy"></path></svg></div></div><div class="go_DOp"><div class="_1psGvi"><div class="YUhWwv"><a class="_3SkBxJ" href="/viewcart?exploreMode=true&amp;preference=FLIPKART"><svg class="V3C5bO" width="14" height="14" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path class="_1bS9ic" d="M15.32 2.405H4.887C3 2.405 2.46.805 2.46.805L2.257.21C2.208.085 2.083 0 1.946 0H.336C.1 0-.064.24.024.46l.644 1.945L3.11 9.767c.047.137.175.23.32.23h8.418l-.493 1.958H3.768l.002.003c-.017 0-.033-.003-.05-.003-1.06 0-1.92.86-1.92 1.92s.86 1.92 1.92 1.92c.99 0 1.805-.75 1.91-1.712l5.55.076c.12.922.91 1.636 1.867 1.636 1.04 0 1.885-.844 1.885-1.885 0-.866-.584-1.593-1.38-1.814l2.423-8.832c.12-.433-.206-.86-.655-.86" fill="#fff"></path></svg><span>Cart</span></a></div></div></div></div><div class="_1TmfNK"></div></div><div class="_1mUdNz"></div></div><div class="_331-kn"></div><div class="_36fx1h _6t1WkM _3HqJxg"><div class="_1YokD2 _2GoDe3"><div class="_1YokD2 _3Mn1Gg col-2-12" style="flex:0 0 280px;max-width:280px;padding:0px 10px 0px 0px"><div class="_1YokD2 _3Mn1Gg col-12-12"><div class="_1AtVbE col-12-12"><div class="_1KOcBL"><section class="JWMl0H _2hbLCH"><div class="_2ssEMF"><div class="_3V8rao"><span>Filters</span></div><div class="_2id1nE"><span>Clear all</span></div></div><div class="_2vLW0p"><div class="_1xc7yr"><div class="_3ztiZO"><div class="_151IuQ">\xe2\x9c\x95</div><div class="_3sckoD">\xe2\x82\xb920000-\xe2\x82\xb930000+</div></div></div><div class="_2w_U27 _2fYv1H"><span>Show  more</span></div></div></section><div class="_2q_g77"><section class="_2aDURW"><div class="_2lfNTw"><span>CATEGORIES</span></div><div><div class="TB_InB"><span><svg width="10" height="10" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="_2Iqv73"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="_3zK8He"></path></svg></span><a class="_2qvBBJ _2Mji8F" title="Mobiles &amp; Accessories" href="/mobiles-accessories/pr?sid=tyy&amp;q=phone&amp;p[]=facets.price_range.from%3D20000&amp;p[]=facets.price_range.to%3DMax&amp;otracker=categorytree">Mobiles &amp; Accessories</a></div></div><div><div class="TB_InB"><span><svg width="10" height="10" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="_2Iqv73"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class=""></path></svg></span><a class="_1jJQdf _2Mji8F" title="Mobiles" href="/mobiles/pr?sid=tyy,4io&amp;q=phone&amp;p[]=facets.price_range.from%3D20000&amp;p[]=facets.price_range.to%3DMax&amp;otracker=categorytree">Mobiles</a></div></div></section></div><section class="_2yz7eI _2hbLCH"><div class="_3KxRU6 _2ssEMF"><div class="UR1L2I _3V8rao"><span>Price</span></div><div class="_3PYmWM _2id1nE"><span>Clear</span></div></div><div class="_2NBiOm"><div class="_1nneZ0"><div class="_2TbXIJ" style="height:0;width:0"></div><div class="_2TbXIJ" style="height:0;width:0"></div><div class="_2TbXIJ" style="height:0;width:0"></div><div class="_2TbXIJ" style="height:0;width:0"></div><div class="_2TbXIJ" style="height:0;width:0"></div></div></div><div class="_2r34SG"><div class="_12FhcQ"><div class="_31Kbhn _28DFQy"><div class="_3FdLqY"></div></div><div class="_31Kbhn WC_zGJ"><div class="_3FdLqY"></div></div><div class="_2IN3-t"></div><div class="_2IN3-t _1mRwrD"></div></div><div class="_15GU70"><div class="_1ftpgI" style="width:undefinedpx">.</div><div class="_1ftpgI" style="width:undefinedpx">.</div><div class="_1ftpgI" style="width:undefinedpx">.</div><div class="_1ftpgI" style="width:undefinedpx">.</div><div class="_1ftpgI" style="width:undefinedpx">.</div><div class="_1ftpgI" style="width:0px">.</div></div></div><div class="_2b0bUo"><div class="_1YAKP4"><select class="_2YxCDZ"><option value="Min" class="_3AsjWR">Min</option><option value="10000" class="_3AsjWR">\xe2\x82\xb910000</option><option value="15000" class="_3AsjWR">\xe2\x82\xb915000</option><option selected="" value="20000" class="_3AsjWR">\xe2\x82\xb920000</option><option value="30000" class="_3AsjWR">\xe2\x82\xb930000</option></select></div><div class="_3zohzR">to</div><div class="_3uDYxP"><select class="_2YxCDZ"><option value="30000" class="_3AsjWR">\xe2\x82\xb930000</option><option selected="" value="Max" class="_3AsjWR">\xe2\x82\xb930000+</option></select></div></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">Brand</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n _3DyGEM"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div><div class="_3FPh42"><div class="_2d0we9"><div class="_2pBqj6"><svg width="20" height="20" viewBox="0 0 17 18" class="_3WAvPc" xmlns="http://www.w3.org/2000/svg"><g fill="#2874F1" fill-rule="evenodd"><path class="-OwdlC" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203"></path><path class="-OwdlC" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467"></path></g></svg><input type="text" value="" class="_34uFYj" placeholder="Search Brand"/></div><div class="_4921Z t0pPfW" title="SAMSUNG"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">SAMSUNG</div></label></div></div><div class="_4921Z t0pPfW" title="APPLE"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">APPLE</div></label></div></div><div class="_4921Z t0pPfW" title="realme"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">realme</div></label></div></div><div class="_4921Z t0pPfW" title="POCO"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">POCO</div></label></div></div><div class="_4921Z t0pPfW" title="Infinix"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">Infinix</div></label></div></div><div class="_4921Z t0pPfW" title="OPPO"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">OPPO</div></label></div></div></div><div class="QvtND5 _2w_U27"><span>25 MORE</span></div></div></section><section class="_2hbLCH _24gLJx"><label class="_2iDkf8 shbqsL"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny _3tCU7L"></div><div class="_3879cV"><div class="_3U-Vxu"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png" class="_3U-Vxu"/></div></div></label><div class="Bv11UC"><span class="question">?</span></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">Customer Ratings</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n _3DyGEM"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div><div class="_3FPh42"><div class="_2d0we9"><div class="_4921Z t0pPfW" title="4\xe2\x98\x85 &amp; above"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">4\xe2\x98\x85 &amp; above</div></label></div></div><div class="_4921Z t0pPfW" title="3\xe2\x98\x85 &amp; above"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">3\xe2\x98\x85 &amp; above</div></label></div></div></div></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">GST Invoice Available</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">RAM</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n _3DyGEM"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div><div class="_3FPh42"><div class="_2d0we9"><div class="_4921Z t0pPfW" title="4 GB"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">4 GB</div></label></div></div><div class="_4921Z t0pPfW" title="3 GB"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">3 GB</div></label></div></div><div class="_4921Z t0pPfW" title="2 GB"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">2 GB</div></label></div></div><div class="_4921Z t0pPfW" title="8 GB and Above"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">8 GB and Above</div></label></div></div><div class="_4921Z t0pPfW" title="1GB and Below"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">1GB and Below</div></label></div></div><div class="_4921Z t0pPfW" title="6 GB"><div class="_1Y4Vhm _4FO7b6"><label class="_2iDkf8 t0pPfW"><input type="checkbox" class="_30VH1S" readonly=""/><div class="_24_Dny"></div><div class="_3879cV">6 GB</div></label></div></div></div></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">Internal Storage</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">Battery Capacity</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">Screen Size</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">Primary Camera</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ttx38n"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="IIvmWM"></path></svg></div></section><section class="_167Mu3 _2hbLCH"><div class="_213eRC _2ssEMF"><div class="_2gmUFU _3V8rao">S

In [8]:
soup = BeautifulSoup(page.content, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <link href="https://rukminim1.flixcart.com" rel="preconnect"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.905c37.css" rel="stylesheet"/>
  <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.914d0a.css" rel="stylesheet"/>
  <meta content="text/html; charset=utf-8" http-equiv="Content-type"/>
  <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
  <meta content="102988293558" property="fb:page_id"/>
  <meta content="658873552,624500995,100000233612389" property="fb:admins"/>
  <meta content="noodp" name="robots"/>
  <link href="https:///www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/>
  <link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/>
  <meta content="website" property="og:type"/>
  <meta content="Flipkart.com" name="og_site_name" property="og:site_name"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
  <link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
  <link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
  <link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
  <link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/>
  <meta content="app" name="twitter:card"/>
  <meta content="@flipkart" name="twitter:site"/>
  <meta content="@flipkart" name="twitter:creator"/>
  <meta content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/>
  <meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/>
  <meta content="in" name="twitter:app:country"/>
  <meta content="Flipkart" name="al:ios:app_name"/>
  <meta content="742044692" name="al:ios:app_store_id"/>
  <meta content="Flipkart" name="twitter:app:name:iphone"/>
  <meta content="742044692" name="twitter:app:id:iphone"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/>
  <meta content="Flipkart" name="twitter:app:name:ipad"/>
  <meta content="742044692" name="twitter:app:id:ipad"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/>
  <meta content="Flipkart" name="twitter:app:name:googleplay"/>
  <meta content="com.flipkart.android" name="twitter:app:id:googleplay"/>
  <meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/>
  <style>
   #container {
			height: 100%;
		}
  </style>
  <link href="///fk-cp-zion/css/Browse.chunk.eb4d21.css" rel="stylesheet"/>
  <title>
   Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com
  </title>
  <meta content="Phone- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title">
   <meta content="Phone" name="Keywords">
    <meta content="Phone- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description">
     <meta content="Phone- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description">
      <meta content="noindex" name="robots">
       <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01">
        <!--[if IE 9 ]>
	<script nonce="15151522127138223793">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]-->
        <!--[if !IE]><!-->
        <script nonce="15151522127138223793">
         if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}
        </script>
        <!--<![endif]-->
        <link href="https://www.flipkart.com/search?q=phone&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;p%5B%5D=facets.price_range.from%3D20000&amp;p%5B%5D=facets.price_range.to%3DMax&amp;page=2" id="next-page-link-tag" rel="next"/>
        <script nonce="15151522127138223793">
         !function(){if("PerformancePaintTiming" in window){var e=window.__perf={e:[]};e.o=new PerformanceObserver(function(n){e.e=e.e.concat(n.getEntries())});try{e.o.observe({entryTypes:["paint"]})}catch(e){}}}();

		if (requestAnimationFrame && performance && performance.mark) {
			requestAnimationFrame(function () {
				window.first_paint = performance.now();
				performance.mark("first_paint");
			});
		}

        // web-vitals polyfill for FID
        !function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);
        </script>
        <script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-594691041">
        </script>
        <script nonce="15151522127138223793">
         window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments)};
		gtag('js', new Date());
        </script>
       </meta>
      </meta>
     </meta>
    </meta>
   </meta>
  </meta>
 </head>
 <body>
  <div id="container">
   <div>
    <div class="_1kfTjk">
     <div class="_1rH5Jn">
      <div class="_1TmfNK">
      </div>
      <div class="_2Xfa2_">
       <div class="_3_C9Hx">
        <div class="_3qX0zy">
         <a href="/">
          <img alt="Flipkart" class="_2xm1JU" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/flipkart-plus_8d85f4.png" title="Flipkart" width="75"/>
         </a>
         <a class="_21ljIi" href="/plus">
          Explore
          <!-- -->
          <span class="_2FVHGh">
           Plus
          </span>
          <img src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/plus_aef861.png" width="10"/>
         </a>
        </div>
       </div>
       <div class="_1cmsER">
        <form action="/search" class="_2M8cLY header-form-search" method="GET">
         <div class="col-12-12 _2oO9oE">
          <div class="_3OO5Xc">
           <input autocomplete="off" class="_3704LK" name="q" placeholder="Search for products, brands and more" title="Search for products, brands and more" type="text" value="phone"/>
          </div>
          <button class="L0Z3Pu" type="submit">
           <svg class="" height="20" viewbox="0 0 17 18" width="20" xmlns="http://www.w3.org/2000/svg">
            <g fill="#2874F1" fill-rule="evenodd">
             <path class="_34RNph" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203">
             </path>
             <path class="_34RNph" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467">
             </path>
            </g>
           </svg>
          </button>
          <input name="otracker" type="hidden" value="search"/>
          <input name="otracker1" type="hidden" value="search"/>
          <input name="marketplace" type="hidden" value="FLIPKART"/>
          <input name="as-show" type="hidden" value="off"/>
          <input name="as" type="hidden" value="off"/>
         </div>
         <ul class="col-12-12 _1MRYA1">
         </ul>
        </form>
       </div>
       <div class="go_DOp _2errNR">
        <div class="_28p97w">
         <div class="_1psGvi _3BvnxG">
          <div>
           <a class="_1_3w1N" href="/account/login?ret=/search%3Fq%3Dphone%26otracker%3Dsearch%26otracker1%3Dsearch%26marketplace%3DFLIPKART%26as-show%3Don%26as%3Doff%26p%255B%255D%3Dfacets.price_range.from%253D20000%26p%255B%255D%3Dfacets.price_range.to%253DMax%26page%3D1">
            Login
           </a>
          </div>
         </div>
        </div>
       </div>
       <div class="go_DOp">
        <a class="_3-PJz-" href="https://seller.flipkart.com/sell-online/?utm_source=fkwebsite&amp;utm_medium=websitedirect">
         <span>
          Become a Seller
         </span>
        </a>
       </div>
       <div class="go_DOp">
        <div class="_28p97w">
         <div class="_1psGvi _3BvnxG">
          <div>
           <div class="exehdJ">
            <!-- -->
            More
            <!-- -->
           </div>
          </div>
         </div>
         <svg class="zZ3yfL" height="8" viewbox="0 0 16 27" width="4.7" xmlns="http://www.w3.org/2000/svg">
          <path class="_2gTTdy" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff">
          </path>
         </svg>
        </div>
       </div>
       <div class="go_DOp">
        <div class="_1psGvi">
         <div class="YUhWwv">
          <a class="_3SkBxJ" href="/viewcart?exploreMode=true&amp;preference=FLIPKART">
           <svg class="V3C5bO" height="14" viewbox="0 0 16 16" width="14" xmlns="http://www.w3.org/2000/svg">
            <path class="_1bS9ic" d="M15.32 2.405H4.887C3 2.405 2.46.805 2.46.805L2.257.21C2.208.085 2.083 0 1.946 0H.336C.1 0-.064.24.024.46l.644 1.945L3.11 9.767c.047.137.175.23.32.23h8.418l-.493 1.958H3.768l.002.003c-.017 0-.033-.003-.05-.003-1.06 0-1.92.86-1.92 1.92s.86 1.92 1.92 1.92c.99 0 1.805-.75 1.91-1.712l5.55.076c.12.922.91 1.636 1.867 1.636 1.04 0 1.885-.844 1.885-1.885 0-.866-.584-1.593-1.38-1.814l2.423-8.832c.12-.433-.206-.86-.655-.86" fill="#fff">
            </path>
           </svg>
           <span>
            Cart
           </span>
          </a>
         </div>
        </div>
       </div>
      </div>
      <div class="_1TmfNK">
      </div>
     </div>
     <div class="_1mUdNz">
     </div>
    </div>
    <div class="_331-kn">
    </div>
    <div class="_36fx1h _6t1WkM _3HqJxg">
     <div class="_1YokD2 _2GoDe3">
      <div class="_1YokD2 _3Mn1Gg col-2-12" style="flex:0 0 280px;max-width:280px;padding:0px 10px 0px 0px">
       <div class="_1YokD2 _3Mn1Gg col-12-12">
        <div class="_1AtVbE col-12-12">
         <div class="_1KOcBL">
          <section class="JWMl0H _2hbLCH">
           <div class="_2ssEMF">
            <div class="_3V8rao">
             <span>
              Filters
             </span>
            </div>
            <div class="_2id1nE">
             <span>
              Clear all
             </span>
            </div>
           </div>
           <div class="_2vLW0p">
            <div class="_1xc7yr">
             <div class="_3ztiZO">
              <div class="_151IuQ">
               ✕
              </div>
              <div class="_3sckoD">
               ₹20000-₹30000+
              </div>
             </div>
            </div>
            <div class="_2w_U27 _2fYv1H">
             <span>
              Show  more
             </span>
            </div>
           </div>
          </section>
          <div class="_2q_g77">
           <section class="_2aDURW">
            <div class="_2lfNTw">
             <span>
              CATEGORIES
             </span>
            </div>
            <div>
             <div class="TB_InB">
              <span>
               <svg class="_2Iqv73" height="10" viewbox="0 0 16 27" width="10" xmlns="http://www.w3.org/2000/svg">
                <path class="_3zK8He" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff">
                </path>
               </svg>
              </span>
              <a class="_2qvBBJ _2Mji8F" href="/mobiles-accessories/pr?sid=tyy&amp;q=phone&amp;p[]=facets.price_range.from%3D20000&amp;p[]=facets.price_range.to%3DMax&amp;otracker=categorytree" title="Mobiles &amp; Accessories">
               Mobiles &amp; Accessories
              </a>
             </div>
            </div>
            <div>
             <div class="TB_InB">
              <span>
               <svg class="_2Iqv73" height="10" viewbox="0 0 16 27" width="10" xmlns="http://www.w3.org/2000/svg">
                <path class="" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff">
                </path>
               </svg>
              </span>
              <a class="_1jJQdf _2Mji8F" href="/mobiles/pr?sid=tyy,4io&amp;q=phone&amp;p[]=facets.price_range.from%3D20000&amp;p[]=facets.price_range.to%3DMax&amp;otracker=categorytree" title="Mobiles">
               Mobiles
              </a>
             </div>
            </div>
           </section>
          </div>
          <section class="_2yz7eI _2hbLCH">
           <div class="_3KxRU6 _2ssEMF">
            <div class="UR1L2I _3V8rao">
             <span>
              Price
             </span>
            </div>
            <div class="_3PYmWM _2id1nE">
             <span>
              Clear
             </span>
            </div>
           </div>
           <div class="_2NBiOm">
            <div class="_1nneZ0">
             <div class="_2TbXIJ" style="height:0;width:0">
             </div>
             <div class="_2TbXIJ" style="height:0;width:0">
             </div>
             <div class="_2TbXIJ" style="height:0;width:0">
             </div>
             <div class="_2TbXIJ" style="height:0;width:0">
             </div>
             <div class="_2TbXIJ" style="height:0;width:0">
             </div>
            </div>
           </div>
           <div class="_2r34SG">
            <div class="_12FhcQ">
             <div class="_31Kbhn _28DFQy">
              <div class="_3FdLqY">
              </div>
             </div>
             <div class="_31Kbhn WC_zGJ">
              <div class="_3FdLqY">
              </div>
             </div>
             <div class="_2IN3-t">
             </div>
             <div class="_2IN3-t _1mRwrD">
             </div>
            </div>
            <div class="_15GU70">
             <div class="_1ftpgI" style="width:undefinedpx">
              .
             </div>
             <div class="_1ftpgI" style="width:undefinedpx">
              .
             </div>
             <div class="_1ftpgI" style="width:undefinedpx">
              .
             </div>
             <div class="_1ftpgI" style="width:undefinedpx">
              .
             </div>
             <div class="_1ftpgI" style="width:undefinedpx">
              .
             </div>
             <div class="_1ftpgI" style="width:0px">
              .
             </div>
            </div>
           </div>
           <div class="_2b0bUo">
            <div class="_1YAKP4">
             <select class="_2YxCDZ">
              <option class="_3AsjWR" value="Min">
               Min
              </option>
              <option class="_3AsjWR" value="10000">
               ₹10000
              </option>
              <option class="_3AsjWR" value="15000">
               ₹15000
              </option>
              <option class="_3AsjWR" selected="" value="20000">
               ₹20000
              </option>
              <option class="_3AsjWR" value="30000">
               ₹30000
              </option>
             </select>
            </div>
            <div class="_3zohzR">
             to
            </div>
            <div class="_3uDYxP">
             <select class="_2YxCDZ">
              <option class="_3AsjWR" value="30000">
               ₹30000
              </option>
              <option class="_3AsjWR" selected="" value="Max">
               ₹30000+
              </option>
             </select>
            </div>
           </div>
          </section>
          <section class="_167Mu3 _2hbLCH">
           <div class="_213eRC _2ssEMF">
            <div class="_2gmUFU _3V8rao">
             Brand
            </div>
            <svg class="ttx38n _3DyGEM" height="27" viewbox="0 0 16 27" width="16" xmlns="http://www.w3.org/2000/svg">
             <path class="IIvmWM" d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff">
             </path>
            </svg>
           </div>
           <div class="_3FPh42">
            <div class="_2d0we9">
             <div class="_2pBqj6">
              <svg class="_3WAvPc" height="20" viewbox="0 0 17 18" width="20" xmlns="http://www.w3.org/2000/svg">
               <g fill="#2874F1" fill-rule="evenodd">
                <path class="-OwdlC" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203">
                </path>
                <path class="-OwdlC" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467">
                </path>
               </g>
              </svg>
              <input class="_34uFYj" placeholder="Search Brand" type="text" value=""/>
             </div>
             <div class="_4921Z t0pPfW" title="SAMSUNG">
              <div class="_1Y4Vhm _4FO7b6">
               <label class="_2iDkf8 t0pPfW">
                <input class="_30VH1S" readonly="" type="checkbox"/>
                <div class="_24_Dny">
                </div>
                <div class="_3879cV">
                 SAMSUNG
                </div>
               </label>
              </div>
             </div>
             <div class="_4921Z t0pPfW" title="APPLE">
              <div class="_1Y4Vhm _4FO7b6">
               <label class="_2iDkf8 t0pPfW">
                <input class="_30VH1S" readonly="" type="checkbox"/>
                <div class="_24_Dny">
                </div>
                <div class="_3879cV">
                 APPLE
                </div>
               </label>
              </div>
             </div>
             <div class="_4921Z t0pPfW" title="realme">
              <div class="_1Y4Vhm _4FO7b6">
               <label class="_2iDkf8 t0pPfW">
                <input class="_30VH1S" readonly="" type="checkbox"/>
                <div class="_24_Dny">
                </div>
                <div class="_3879cV">
                 realme
                </div>
               </label>
              </div>
             </div>
             <div class="_4921Z t0pPfW" title="POCO">
              <div class="_1Y4Vhm _4FO7b6">
               <label class="_2iDkf8 t0pPfW">
                <input class="_30VH1S" readonly="" type="checkbox"/>
                <div class="_24_Dny">
                </div>
                <div class="_3879cV">
                 POCO
                </div>
               </label>
              </div>
             </div>
             <div class="_4921Z t0pPfW" title="Infinix">
              <div class="_1Y4Vhm _4FO7b6">
               <label class="_2iDkf8 t0pPfW">
                <input class="_30VH1S" readonly="" type="checkbox"/>
                <div class="_24_Dny">
                </div>
                <div class="_3879cV">
                 Infinix
                </div>
               </label>
              </div>
             </div>
             <div class="_4921Z t0pPfW" title="OPPO">
              <div class="_1Y4Vhm _4FO7b6">
               <label class="_2iDkf8 t0pPfW">
                <input class="_30VH1S" readonly="" type="checkbox"/>
                <div class="_24_Dny">
                </div>
                <div class="_3879cV">
                 OPPO
                </div>
               </label>

In [9]:
name = soup.find('div', class_ = '_4rR01T')
name

In [10]:
name.text

'vivo T2 5G (Velocity Wave, 128 GB)'

In [11]:
price = soup.find('div', class_ = '_30jeq3 _1_WHN1')
price.text

'₹20,999'

In [12]:
rating = soup.find('div', class_ = '_3LWZlK')
rating.text

'4.4'

In [13]:
ratings_reviews = soup.find('span', class_ = '_2_R_DZ')
ratings_reviews.text

'4,509 Ratings\xa0&\xa0301 Reviews'

In [14]:
specifications = soup.find('div', class_ = 'fMghEO')
specifications

<div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">8 GB RAM | 128 GB ROM</li><li class="rgWa7D">16.21 cm (6.38 inch) Full HD+ Display</li><li class="rgWa7D">64 MP (OIS) + 2MP | 16MP Front Camera</li><li class="rgWa7D">4500 mAh Battery</li><li class="rgWa7D">Snapdragon 695 Processor</li><li class="rgWa7D">1 Year of Device &amp; 6 Months for Inbox Accessories</li></ul></div>

In [15]:
specs = specifications.find_all('li', class_ = 'rgWa7D')
specs

[<li class="rgWa7D">8 GB RAM | 128 GB ROM</li>,
 <li class="rgWa7D">16.21 cm (6.38 inch) Full HD+ Display</li>,
 <li class="rgWa7D">64 MP (OIS) + 2MP | 16MP Front Camera</li>,
 <li class="rgWa7D">4500 mAh Battery</li>,
 <li class="rgWa7D">Snapdragon 695 Processor</li>,
 <li class="rgWa7D">1 Year of Device &amp; 6 Months for Inbox Accessories</li>]

In [16]:
print(len(specs))
print(specs[0].text)
print(specs[1].text)
print(specs[2].text)
print(specs[3].text)
print(specs[4].text)
#print(specs[5].text)

6
8 GB RAM | 128 GB ROM
16.21 cm (6.38 inch) Full HD+ Display
64 MP (OIS) + 2MP | 16MP Front Camera
4500 mAh Battery
Snapdragon 695 Processor

In [17]:
# Extracting product details of all the products on the webpage
product_details = soup.find_all('div', class_ = '_3pLy-c row')
print(len(product_details))
product_details

24

[<div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">vivo T2 5G (Velocity Wave, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGZBFU2GHZTMGNA9LEX4_MOBGZBFU2GHZTMGN_"><div class="_3LWZlK">4.4<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>4,509 Ratings </span><span class="_13vcmD">&amp;</span><span> 301 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">8 GB RAM | 128 GB ROM</li><li class="rgWa7D">16.21 cm (6.38 inch) Full HD+ Display</li><li class="rgWa7D">64 MP (OIS) + 2MP | 16MP Front Camera</li><li class="rgWa7D">4500 mAh Battery</li><li class="rgWa7D">Snapdragon 695 Processor</li><li class="rgWa7D">1 Year of Device &amp; 6 Months for Inbox Accessories</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹20,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->24,999</div><div class="_3Ay6Sb"><span>16% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹19,750</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:12px;font-weight:400">No Cost EMI from ₹7,000/month</div></div></div></div></div>,
 <div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">vivo T2 5G (Nitro Blaze, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGZBFUHGYHNEMBAEJO4M_MOBGZBFUHGYHNEMB_"><div class="_3LWZlK">4.4<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>4,509 Ratings </span><span class="_13vcmD">&amp;</span><span> 301 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">8 GB RAM | 128 GB ROM</li><li class="rgWa7D">16.21 cm (6.38 inch) Full HD+ Display</li><li class="rgWa7D">64 MP (OIS) + 2MP | 16MP Front Camera</li><li class="rgWa7D">4500 mAh Battery</li><li class="rgWa7D">Snapdragon 695 Processor</li><li class="rgWa7D">1 Year of Device &amp; 6 Months for Inbox Accessories</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹20,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->24,999</div><div class="_3Ay6Sb"><span>16% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹19,750</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:12px;font-weight:400">No Cost EMI from ₹7,000/month</div></div></div></div></div>,
 <div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">APPLE iPhone 14 (Midnight, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGHWFHECFVMDCX8AI8PX_MOBGHWFHECFVMDCX_"><div class="_3LWZlK">4.6<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>37,021 Ratings </span><span class="_13vcmD">&amp;</span><span> 1,428 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">128 GB ROM</li><li class="rgWa7D">15.49 cm (6.1 inch) Super Retina XDR Display</li><li class="rgWa7D">12MP + 12MP | 12MP Front Camera</li><li class="rgWa7D">A15 Bionic Chip, 6 Core Processor Processor</li><li class="rgWa7D">1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹69,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->79,900</div><div class="_3Ay6Sb"><span>12% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#26A541;font-size:12px;font-weight:700">Daily Saver</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹35,000</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div></div></div>,
 <div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">APPLE iPhone 14 (Purple, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGHWFHQFSQYBFU9AP8AR_MOBGHWFHQFSQYBFU_"><div class="_3LWZlK">4.6<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>37,021 Ratings </span><span class="_13vcmD">&amp;</span><span> 1,428 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">128 GB ROM</li><li class="rgWa7D">15.49 cm (6.1 inch) Super Retina XDR Display</li><li class="rgWa7D">12MP + 12MP | 12MP Front Camera</li><li class="rgWa7D">A15 Bionic Chip, 6 Core Processor Processor</li><li class="rgWa7D">1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹69,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->79,900</div><div class="_3Ay6Sb"><span>12% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#26A541;font-size:12px;font-weight:700">Daily Saver</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹35,000</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div></div></div>,
 <div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">APPLE iPhone 14 (Starlight, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGHWFHABH3G73HVXY5AV_MOBGHWFHABH3G73H_"><div class="_3LWZlK">4.6<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>37,021 Ratings </span><span class="_13vcmD">&amp;</span><span> 1,428 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">128 GB ROM</li><li class="rgWa7D">15.49 cm (6.1 inch) Super Retina XDR Display</li><li class="rgWa7D">12MP + 12MP | 12MP Front Camera</li><li class="rgWa7D">A15 Bionic Chip, 6 Core Processor Processor</li><li class="rgWa7D">1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹69,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->79,900</div><div class="_3Ay6Sb"><span>12% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#26A541;font-size:12px;font-weight:700">Daily Saver</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹35,000</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div></div></div>,
 <div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">Google Pixel 6a (Charcoal, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGFKX5YUXD74Z3MXA2OB_MOBGFKX5YUXD74Z3_"><div class="_3LWZlK">4.3<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>46,804 Ratings </span><span class="_13vcmD">&amp;</span><span> 5,621 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">6 GB RAM | 128 GB ROM</li><li class="rgWa7D">15.6 cm (6.14 inch) Full HD+ Display</li><li class="rgWa7D">12.2MP + 12MP | 8MP Front Camera</li><li class="rgWa7D">4410 mAh Battery</li><li class="rgWa7D">Google Tensor Processor</li><li class="rgWa7D">1 Year Brand Warranty</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹28,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->43,999</div><div class="_3Ay6Sb"><span>34% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹28,200</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:12px;font-weight:400">No Cost EMI from ₹4,834/month</div></div></div></div></div>,
 <div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">Google Pixel 6a (Chalk, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGFWEZ5SKU84Z8FXPB45_MOBGFWEZ5SKU84Z8_"><div class="_3LWZlK">4.3<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>46,804 Ratings </span><span class="_13vcmD">&amp;</span><span> 5,621 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">6 GB RAM | 128 GB ROM</li><li class="rgWa7D">15.6 cm (6.14 inch) Full HD+ Display</li><li class="rgWa7D">12.2MP + 12MP | 8MP Front Camera</li><li class="rgWa7D">4410 mAh Battery</li><li class="rgWa7D">Google Tensor Processor</li><li class="rgWa7D">1 Year Brand Warranty</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹28,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->43,999</div><div class="_3Ay6Sb"><span>34% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹28,200</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:12px;font-weight:400">No Cost EMI from ₹4,834/month</div></div></div></div></div>,
 <div class="_3pLy-c row"><div class="col col-7-12"><div class="_4rR01T">realme GT 2 (Steel Black, 128 GB)</div><div class="gUuXy-"><span class="_1lRcqv" id="productRating_LSTMOBGDAT7ATJAFSXZYNJKAX_MOBGDAT7ATJAFSXZ_"><div class="_3LWZlK">4.3<img class="_1wB99o" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div></span><span class="_2_R_DZ"><span><span>9,610 Ratings </span><span class="_13vcmD">&amp;</span><span> 1,131 Reviews</span></span></span></div><div class="fMghEO"><ul class="_1xgFaf"><li class="rgWa7D">8 GB RAM | 128 GB ROM</li><li class="rgWa7D">16.81 cm (6.62 inch) Full HD+ AMOLED Display</li><li class="rgWa7D">50MP + 8MP + 2MP | 16MP Front Camera</li><li class="rgWa7D">5000 mAh Lithium Ion Battery</li><li class="rgWa7D">Qualcomm Snapdragon 888 Processor</li><li class="rgWa7D">1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories</li></ul></div></div><div class="col col-5-12 nlI3QM"><div class="_3tbKJL"><div class="_25b18c"><div class="_30jeq3 _1_WHN1">₹23,999</div><div class="_3I9_wc _27UcVY">₹<!-- -->39,999</div><div class="_3Ay6Sb"><span>40% off</span></div></div><div class="_3tcB5a p8ucoS"><div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-weight:400">Free delivery by</div><div class="_2Tpdn3" style="color:#000000;font-size:12px;font-style:normal;font-weight:700"> Today</div></div></div></div><div class="_13J9qT"><img height="21" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/fa_62673a.png"/></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#26A541;font-size:12px;font-weight:700">Lowest price in the year</div></div></div><div class="_2ZdXDB"><div class="_3xFhiH"><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400">Upto </div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:700">₹23,400</div><div class="_2Tpdn3 _18hQoS" style="color:#000000;font-size:14px;font-style:normal;font-weight:400"> Off on Exchange</div></div></div></div></div>,

In [18]:
# Showing product details one by one
for product in product_details:
    # name
    name = product.find('div', class_ = '_4rR01T')
    if name is None:
        print('Name not available')
    else:
        print(name.text)
        
    # price
    price = product.find('div', class_ = '_30jeq3 _1_WHN1')
    if price is None:
        print('Price not available')
    else:
        print(price.text)
        
    # rating
    rating = product.find('div', class_ = '_3LWZlK')
    if rating is None:
        print('Rating not available')
    else:
        print(rating.text)
        
    # ratings and reviews
    ratings_reviews = product.find('span', class_ = '_2_R_DZ')
    if ratings_reviews is None:
        print('Number of Ratings and reviews not available')
    else:
        print(ratings_reviews.text)
        
    # specifications
    features = []
    specifications = product.find('div', class_ = 'fMghEO')
    specs = specifications.find_all('li', class_ = 'rgWa7D')
    for feature in specs:
        features.append(feature.text)
    print(features)
    
    print('=' * 100)
    print()

vivo T2 5G (Velocity Wave, 128 GB)
₹20,999
4.4
4,509 Ratings & 301 Reviews
['8 GB RAM | 128 GB ROM', '16.21 cm (6.38 inch) Full HD+ Display', '64 MP (OIS) + 2MP | 16MP Front Camera', '4500 mAh Battery', 'Snapdragon 695 Processor', '1 Year of Device & 6 Months for Inbox Accessories']
====================================================================================================

vivo T2 5G (Nitro Blaze, 128 GB)
₹20,999
4.4
4,509 Ratings & 301 Reviews
['8 GB RAM | 128 GB ROM', '16.21 cm (6.38 inch) Full HD+ Display', '64 MP (OIS) + 2MP | 16MP Front Camera', '4500 mAh Battery', 'Snapdragon 695 Processor', '1 Year of Device & 6 Months for Inbox Accessories']
====================================================================================================

APPLE iPhone 14 (Midnight, 128 GB)
₹69,999
4.6
37,021 Ratings & 1,428 Reviews
['128 GB ROM', '15.49 cm (6.1 inch) Super Retina XDR Display', '12MP + 12MP | 12MP Front Camera', 'A15 Bionic Chip, 6 Core Processor Processor', '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories']
====================================================================================================

APPLE iPhone 14 (Purple, 128 GB)
₹69,999
4.6
37,021 Ratings & 1,428 Reviews
['128 GB ROM', '15.49 cm (6.1 inch) Super Retina XDR Display', '12MP + 12MP | 12MP Front Camera', 'A15 Bionic Chip, 6 Core Processor Processor', '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories']
====================================================================================================

APPLE iPhone 14 (Starlight, 128 GB)
₹69,999
4.6
37,021 Ratings & 1,428 Reviews
['128 GB ROM', '15.49 cm (6.1 inch) Super Retina XDR Display', '12MP + 12MP | 12MP Front Camera', 'A15 Bionic Chip, 6 Core Processor Processor', '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories']
====================================================================================================

Google Pixel 6a (Charcoal, 128 GB)
₹28,999
4.3
46,804 Ratings & 5,621 Reviews
['6 GB RAM | 128 GB ROM', '15.6 cm (6.14 inch) Full HD+ Display', '12.2MP + 12MP | 8MP Front Camera', '4410 mAh Battery', 'Google Tensor Processor', '1 Year Brand Warranty']
====================================================================================================

Google Pixel 6a (Chalk, 128 GB)
₹28,999
4.3
46,804 Ratings & 5,621 Reviews
['6 GB RAM | 128 GB ROM', '15.6 cm (6.14 inch) Full HD+ Display', '12.2MP + 12MP | 8MP Front Camera', '4410 mAh Battery', 'Google Tensor Processor', '1 Year Brand Warranty']
====================================================================================================

realme GT 2 (Steel Black, 128 GB)
₹23,999
4.3
9,610 Ratings & 1,131 Reviews
['8 GB RAM | 128 GB ROM', '16.81 cm (6.62 inch) Full HD+ AMOLED Display', '50MP + 8MP + 2MP | 16MP Front Camera', '5000 mAh Lithium Ion Battery', 'Qualcomm Snapdragon 888 Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories']
====================================================================================================

POCO X5 Pro 5G (Horizon Blue, 256 GB)
₹23,999
4.3
7,800 Ratings & 821 Reviews
['8 GB RAM | 256 GB ROM', '16.94 cm (6.67 inch) Full HD+ Display', '108MP + 8MP + 2MP | 16MP Front Camera', '5000 mAh Battery', 'Qualcomm Snapdragon 778G Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box Accessories']
====================================================================================================

APPLE iPhone 13 (Green, 128 GB)
₹61,999
4.7
2,25,513 Ratings & 11,650 Reviews
['128 GB ROM', '15.49 cm (6.1 inch) Super Retina XDR Display', '12MP + 12MP | 12MP Front Camera', 'A15 Bionic Chip Processor', 'Brand Warranty for 1 Year']
====================================================================================================

POCO X5 Pro 5G (Astral Black, 256 GB)
₹23,999
4.3
7,800 Ratings & 821 Reviews
['8 GB RAM | 256 GB ROM', '16.94 cm (6.67 inch) Full HD+ Display', '108MP + 8MP + 2MP | 16MP Front Camera', '5000 mAh Battery', 'Qualcomm Snapdragon 778G Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box Accessories']
====================================================================================================

REDMI K50i 5G (Stealth Black, 256 GB)
₹23,999
4.2
871 Ratings & 90 Reviews
['8 GB RAM | 256 GB ROM', '16.76 cm (6.6 inch) Full HD+ Display', '64MP + 8MP + 2MP | 16MP Front Camera', '5080 mAh Battery', 'Dimensity 8100 Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']
====================================================================================================

vivo V27 5G (Noble Black, 128 GB)
₹32,999
4.4
14,254 Ratings & 1,677 Reviews
['8 GB RAM | 128 GB ROM', '17.22 cm (6.78 Inch) Full HD+ AMOLED Display', '50MP (OIS) + 8MP + 2MP | 50MP Front Camera', '4600 mAh Battery', 'Mediatek Dimensity 7200 5G Processor', '1 Year Brand Warranty']
====================================================================================================

REDMI Note 12 Pro 5G (Stardust Purple, 128 GB)
₹23,999
4.3
23,532 Ratings & 2,311 Reviews
['6 GB RAM | 128 GB ROM', '16.94 cm (6.67 inch) Full HD Display', '50MP (OIS) + 8MP + 2MP | 16MP Front Camera', '5000 mAh Lithium Polymer Battery', 'Mediatek Dimensity 1080 Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']
====================================================================================================

SAMSUNG Galaxy M33 5G (Deep Ocean Blue, 128 GB)
₹20,691
4.2
2,556 Ratings & 177 Reviews
['8 GB RAM | 128 GB ROM', '16.76 cm (6.6 inch) Display', '50MP Rear Camera', '6000 mAh Battery', '1 Year Warranty']
====================================================================================================

APPLE iPhone 14 (Blue, 128 GB)
₹69,999
4.6
37,021 Ratings & 1,428 Reviews
['128 GB ROM', '15.49 cm (6.1 inch) Super Retina XDR Display', '12MP + 12MP | 12MP Front Camera', 'A15 Bionic Chip, 6 Core Processor Processor', '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories']
====================================================================================================

SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128 GB)
₹49,999
4.5
3,299 Ratings & 372 Reviews
['8 GB RAM | 128 GB ROM', '16.76 cm (6.6 inch) Full HD+ Display', '50MP + 12MP + 10MP | 10MP Front Camera', '4500 mAh Lithium-ion Battery', 'Qualcomm Snapdragon 8 Gen 1 Processor', '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories']
====================================================================================================

vivo V27 5G (Magic Blue, 128 GB)
₹32,999
4.4
14,254 Ratings & 1,677 Reviews
['8 GB RAM | 128 GB ROM', '17.22 cm (6.78 Inch) Full HD+ AMOLED Display', '50MP (OIS) + 8MP + 2MP | 50MP Front Camera', '4600 mAh Battery', 'Mediatek Dimensity 7200 5G Processor', '1 Year Brand Warranty']
====================================================================================================

REDMI Note 12 Pro 5G (Glacier Blue, 128 GB)
₹23,999
4.3
23,532 Ratings & 2,311 Reviews
['6 GB RAM | 128 GB ROM', '16.94 cm (6.67 inch) Full HD Display', '50MP (OIS) + 8MP + 2MP | 16MP Front Camera', '5000 mAh Lithium Polymer Battery', 'Mediatek Dimensity 1080 Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']
====================================================================================================

POCO X5 Pro 5G (Horizon Blue, 128 GB)
₹21,999
4.3
8,165 Ratings & 899 Reviews
['6 GB RAM | 128 GB ROM', '16.94 cm (6.67 inch) Full HD+ Display', '108MP + 8MP + 2MP | 16MP Front Camera', '5000 mAh Battery', 'Qualcomm Snapdragon 778G Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box Accessories']
====================================================================================================

SAMSUNG Galaxy M33 5G (Mystique Green, 128 GB)
₹20,990
4.2
10,333 Ratings & 770 Reviews
['6 GB RAM | 128 GB ROM', '16.74 cm (6.59 inch) Display', '50MP Rear Camera', '6000 mAh Battery', '12 Months Warranty']
====================================================================================================

REDMI Note 12 Pro 5G (Stardust Purple, 256 GB)
₹26,999
4.2
10,198 Ratings & 987 Reviews
['8 GB RAM | 256 GB ROM', '16.94 cm (6.67 inch) Full HD Display', '50MP (OIS) + 8MP + 2MP | 16MP Front Camera', '5000 mAh Lithium Polymer Battery', 'Mediatek Dimensity 1080 Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']
====================================================================================================

OnePlus Nord 2T 5G (Gray Shadow, 128 GB)
₹27,738
4.3
8,983 Ratings & 752 Reviews
['8 GB RAM | 128 GB ROM', '17.02 cm (6.7 inch) Display', '50MP Rear Camera', '4500 mAh Battery', '12 Month']
====================================================================================================

REDMI Note 12 Pro+ 5G (Obsidian Black, 256 GB)
₹29,999
4.3
11,315 Ratings & 1,211 Reviews
['8 GB RAM | 256 GB ROM', '16.94 cm (6.67 inch) Full HD+ Display', '200MP + 8MP + 2MP | 16MP Front Camera', '4980 mAh Lithium Polymer Battery', 'Mediatek Dimensity 1080 Processor', '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']
====================================================================================================

# Scraping and storing details of a single webpage

In [19]:
# Storing information in lists
titles = []
prices = []
ratings = []
RnR = []
features = []

# Extracting product details of all products on the webpage
product_details = soup.find_all('div', class_ = '_3pLy-c row')

for product in product_details:
    # name
    name = product.find('div', class_ = '_4rR01T')
    if name is None:
        titles.append(np.nan)
    else:
        titles.append(name.text)
        
    # price
    price = product.find('div', class_ = '_30jeq3 _1_WHN1')
    if price is None:
        prices.append(np.nan)
    else:
        prices.append(price.text)
        
    # rating
    rating = product.find('div', class_ = '_3LWZlK')
    if rating is None:
        ratings.append(np.nan)
    else:
        ratings.append(rating.text)
        
    # ratings and reviews
    ratings_reviews = product.find('span', class_ = '_2_R_DZ')
    if ratings_reviews is None:
        RnR.append(np.nan)
    else:
        RnR.append(ratings_reviews.text)
        
    # specifications
    f = []
    specifications = product.find('div', class_ = 'fMghEO')
    specs = specifications.find_all('li', class_ = 'rgWa7D')
    for feature in specs:
        f.append(feature.text)
    features.append(f)

In [20]:
print(len(titles))
print(len(prices))
print(len(ratings))
print(len(RnR))
print(len(features))

24
24
24
24
24

In [21]:
print(titles)
print()
print(prices)
print()
print(ratings)
print()
print(RnR)

['vivo T2 5G (Velocity Wave, 128 GB)', 'vivo T2 5G (Nitro Blaze, 128 GB)', 'APPLE iPhone 14 (Midnight, 128 GB)', 'APPLE iPhone 14 (Purple, 128 GB)', 'APPLE iPhone 14 (Starlight, 128 GB)', 'Google Pixel 6a (Charcoal, 128 GB)', 'Google Pixel 6a (Chalk, 128 GB)', 'realme GT 2 (Steel Black, 128 GB)', 'POCO X5 Pro 5G (Horizon Blue, 256 GB)', 'APPLE iPhone 13 (Green, 128 GB)', 'POCO X5 Pro 5G (Astral Black, 256 GB)', 'REDMI K50i 5G (Stealth Black, 256 GB)', 'vivo V27 5G (Noble Black, 128 GB)', 'REDMI Note 12 Pro 5G (Stardust Purple, 128 GB)', 'SAMSUNG Galaxy M33 5G (Deep Ocean Blue, 128 GB)', 'APPLE iPhone 14 (Blue, 128 GB)', 'SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128 GB)', 'vivo V27 5G (Magic Blue, 128 GB)', 'REDMI Note 12 Pro 5G (Glacier Blue, 128 GB)', 'POCO X5 Pro 5G (Horizon Blue, 128 GB)', 'SAMSUNG Galaxy M33 5G (Mystique Green, 128 GB)', 'REDMI Note 12 Pro 5G (Stardust Purple, 256 GB)', 'OnePlus Nord 2T 5G (Gray Shadow, 128 GB)', 'REDMI Note 12 Pro+ 5G (Obsidian Black, 256 GB)']

['₹20,999', '₹20,999', '₹69,999', '₹69,999', '₹69,999', '₹28,999', '₹28,999', '₹23,999', '₹23,999', '₹61,999', '₹23,999', '₹23,999', '₹32,999', '₹23,999', '₹20,691', '₹69,999', '₹49,999', '₹32,999', '₹23,999', '₹21,999', '₹20,990', '₹26,999', '₹27,738', '₹29,999']

['4.4', '4.4', '4.6', '4.6', '4.6', '4.3', '4.3', '4.3', '4.3', '4.7', '4.3', '4.2', '4.4', '4.3', '4.2', '4.6', '4.5', '4.4', '4.3', '4.3', '4.2', '4.2', '4.3', '4.3']

['4,509 Ratings\xa0&\xa0301 Reviews', '4,509 Ratings\xa0&\xa0301 Reviews', '37,021 Ratings\xa0&\xa01,428 Reviews', '37,021 Ratings\xa0&\xa01,428 Reviews', '37,021 Ratings\xa0&\xa01,428 Reviews', '46,804 Ratings\xa0&\xa05,621 Reviews', '46,804 Ratings\xa0&\xa05,621 Reviews', '9,610 Ratings\xa0&\xa01,131 Reviews', '7,800 Ratings\xa0&\xa0821 Reviews', '2,25,513 Ratings\xa0&\xa011,650 Reviews', '7,800 Ratings\xa0&\xa0821 Reviews', '871 Ratings\xa0&\xa090 Reviews', '14,254 Ratings\xa0&\xa01,677 Reviews', '23,532 Ratings\xa0&\xa02,311 Reviews', '2,556 Ratings\xa0&\xa0177 Reviews', '37,021 Ratings\xa0&\xa01,428 Reviews', '3,299 Ratings\xa0&\xa0372 Reviews', '14,254 Ratings\xa0&\xa01,677 Reviews', '23,532 Ratings\xa0&\xa02,311 Reviews', '8,165 Ratings\xa0&\xa0899 Reviews', '10,333 Ratings\xa0&\xa0770 Reviews', '10,198 Ratings\xa0&\xa0987 Reviews', '8,983 Ratings\xa0&\xa0752 Reviews', '11,315 Ratings\xa0&\xa01,211 Reviews']

In [22]:
features

[['8 GB RAM | 128 GB ROM',
  '16.21 cm (6.38 inch) Full HD+ Display',
  '64 MP (OIS) + 2MP | 16MP Front Camera',
  '4500 mAh Battery',
  'Snapdragon 695 Processor',
  '1 Year of Device & 6 Months for Inbox Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '16.21 cm (6.38 inch) Full HD+ Display',
  '64 MP (OIS) + 2MP | 16MP Front Camera',
  '4500 mAh Battery',
  'Snapdragon 695 Processor',
  '1 Year of Device & 6 Months for Inbox Accessories'],
 ['128 GB ROM',
  '15.49 cm (6.1 inch) Super Retina XDR Display',
  '12MP + 12MP | 12MP Front Camera',
  'A15 Bionic Chip, 6 Core Processor Processor',
  '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories'],
 ['128 GB ROM',
  '15.49 cm (6.1 inch) Super Retina XDR Display',
  '12MP + 12MP | 12MP Front Camera',
  'A15 Bionic Chip, 6 Core Processor Processor',
  '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories'],
 ['128 GB ROM',
  '15.49 cm (6.1 inch) Super Retina XDR Display',
  '12MP + 12MP | 12MP Front Camera',
  'A15 Bionic Chip, 6 Core Processor Processor',
  '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories'],
 ['6 GB RAM | 128 GB ROM',
  '15.6 cm (6.14 inch) Full HD+ Display',
  '12.2MP + 12MP | 8MP Front Camera',
  '4410 mAh Battery',
  'Google Tensor Processor',
  '1 Year Brand Warranty'],
 ['6 GB RAM | 128 GB ROM',
  '15.6 cm (6.14 inch) Full HD+ Display',
  '12.2MP + 12MP | 8MP Front Camera',
  '4410 mAh Battery',
  'Google Tensor Processor',
  '1 Year Brand Warranty'],
 ['8 GB RAM | 128 GB ROM',
  '16.81 cm (6.62 inch) Full HD+ AMOLED Display',
  '50MP + 8MP + 2MP | 16MP Front Camera',
  '5000 mAh Lithium Ion Battery',
  'Qualcomm Snapdragon 888 Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In-Box Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '16.94 cm (6.67 inch) Full HD+ Display',
  '108MP + 8MP + 2MP | 16MP Front Camera',
  '5000 mAh Battery',
  'Qualcomm Snapdragon 778G Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box Accessories'],
 ['128 GB ROM',
  '15.49 cm (6.1 inch) Super Retina XDR Display',
  '12MP + 12MP | 12MP Front Camera',
  'A15 Bionic Chip Processor',
  'Brand Warranty for 1 Year'],
 ['8 GB RAM | 256 GB ROM',
  '16.94 cm (6.67 inch) Full HD+ Display',
  '108MP + 8MP + 2MP | 16MP Front Camera',
  '5000 mAh Battery',
  'Qualcomm Snapdragon 778G Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box Accessories'],
 ['8 GB RAM | 256 GB ROM',
  '16.76 cm (6.6 inch) Full HD+ Display',
  '64MP + 8MP + 2MP | 16MP Front Camera',
  '5080 mAh Battery',
  'Dimensity 8100 Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '17.22 cm (6.78 Inch) Full HD+ AMOLED Display',
  '50MP (OIS) + 8MP + 2MP | 50MP Front Camera',
  '4600 mAh Battery',
  'Mediatek Dimensity 7200 5G Processor',
  '1 Year Brand Warranty'],
 ['6 GB RAM | 128 GB ROM',
  '16.94 cm (6.67 inch) Full HD Display',
  '50MP (OIS) + 8MP + 2MP | 16MP Front Camera',
  '5000 mAh Lithium Polymer Battery',
  'Mediatek Dimensity 1080 Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '16.76 cm (6.6 inch) Display',
  '50MP Rear Camera',
  '6000 mAh Battery',
  '1 Year Warranty'],
 ['128 GB ROM',
  '15.49 cm (6.1 inch) Super Retina XDR Display',
  '12MP + 12MP | 12MP Front Camera',
  'A15 Bionic Chip, 6 Core Processor Processor',
  '1 Year Warranty for Phone and 6 Months Warranty for In-Box Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '16.76 cm (6.6 inch) Full HD+ Display',
  '50MP + 12MP + 10MP | 10MP Front Camera',
  '4500 mAh Lithium-ion Battery',
  'Qualcomm Snapdragon 8 Gen 1 Processor',
  '1 Year Manufacturer Warranty for Device and 6 Months Manufacturer Warranty for In-Box Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '17.22 cm (6.78 Inch) Full HD+ AMOLED Display',
  '50MP (OIS) + 8MP + 2MP | 50MP Front Camera',
  '4600 mAh Battery',
  'Mediatek Dimensity 7200 5G Processor',
  '1 Year Brand Warranty'],
 ['6 GB RAM | 128 GB ROM',
  '16.94 cm (6.67 inch) Full HD Display',
  '50MP (OIS) + 8MP + 2MP | 16MP Front Camera',
  '5000 mAh Lithium Polymer Battery',
  'Mediatek Dimensity 1080 Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories'],
 ['6 GB RAM | 128 GB ROM',
  '16.94 cm (6.67 inch) Full HD+ Display',
  '108MP + 8MP + 2MP | 16MP Front Camera',
  '5000 mAh Battery',
  'Qualcomm Snapdragon 778G Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for in the Box Accessories'],
 ['6 GB RAM | 128 GB ROM',
  '16.74 cm (6.59 inch) Display',
  '50MP Rear Camera',
  '6000 mAh Battery',
  '12 Months Warranty'],
 ['8 GB RAM | 256 GB ROM',
  '16.94 cm (6.67 inch) Full HD Display',
  '50MP (OIS) + 8MP + 2MP | 16MP Front Camera',
  '5000 mAh Lithium Polymer Battery',
  'Mediatek Dimensity 1080 Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories'],
 ['8 GB RAM | 128 GB ROM',
  '17.02 cm (6.7 inch) Display',
  '50MP Rear Camera',
  '4500 mAh Battery',
  '12 Month'],
 ['8 GB RAM | 256 GB ROM',
  '16.94 cm (6.67 inch) Full HD+ Display',
  '200MP + 8MP + 2MP | 16MP Front Camera',
  '4980 mAh Lithium Polymer Battery',
  'Mediatek Dimensity 1080 Processor',
  '1 Year Manufacturer Warranty for Phone and 6 Months Warranty for In the Box Accessories']]

# Scraping and storing details for 20 webpages

In [58]:
# Storing information in lists
titles = []
prices = []
ratings = []
RnR = []
features = []
pgno = []

# loop to go through webpages
for x in range(1,11):
    start_time = time.time()
    
    URL = 'https://www.flipkart.com/search?q=phone&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&p%5B%5D=facets.price_range.from%3D20000&p%5B%5D=facets.price_range.to%3DMax&page={}'.format(x)
    page = requests.get(URL)
    soup = BeautifulSoup(page.content, 'html.parser')
    
    # Extracting product details of all products on the webpage
    product_details = soup.find_all('div', class_ = '_3pLy-c row')

    for product in product_details:
        # name
        name = product.find('div', class_ = '_4rR01T')
        if name is None:
            titles.append(np.nan)
        else:
            titles.append(name.text)

        # price
        price = product.find('div', class_ = '_30jeq3 _1_WHN1')
        if price is None:
            prices.append(np.nan)
        else:
            prices.append(price.text)

        # rating
        rating = product.find('div', class_ = '_3LWZlK')
        if rating is None:
            ratings.append(np.nan)
        else:
            ratings.append(rating.text)

        # ratings and reviews
        ratings_reviews = product.find('span', class_ = '_2_R_DZ')
        if ratings_reviews is None:
            RnR.append(np.nan)
        else:
            RnR.append(ratings_reviews.text)

        # specifications
        f = []
        specifications = product.find('div', class_ = 'fMghEO')
        specs = specifications.find_all('li', class_ = 'rgWa7D')
        for feature in specs:
            f.append(feature.text)
        features.append(f)
        
        # page number
        pgno.append(x)
        
    end_time = time.time()
    print('Page {} completed in {} seconds'.format(x, end_time - start_time))

Page 1 completed in 1.358246088027954 seconds
Page 2 completed in 2.529066562652588 seconds
Page 3 completed in 1.829512596130371 seconds
Page 4 completed in 2.591153860092163 seconds
Page 5 completed in 1.1636974811553955 seconds
Page 6 completed in 1.8769192695617676 seconds
Page 7 completed in 1.5509450435638428 seconds
Page 8 completed in 1.6950480937957764 seconds
Page 9 completed in 1.9242987632751465 seconds
Page 10 completed in 1.3985402584075928 seconds

In [59]:
print(len(titles))
print(len(prices))
print(len(ratings))
print(len(RnR))
print(len(features))

240
240
240
240
240

# Creating a dataframe

In [60]:
data = {'Product_name' : titles,
        'Price'        : prices,
        'Rating'       : ratings,
        'No_of_RnR'    : RnR,
        'Features'     : features}

df = pd.DataFrame(data)
df.head(10)

,Product_name,Price,Rating,No_of_RnR,Features
0,"vivo T2 5G (Velocity Wave, 128 GB)","₹20,999",4.4,"4,509 Ratings & 301 Reviews","[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F..."
1,"vivo T2 5G (Nitro Blaze, 128 GB)","₹20,999",4.4,"4,509 Ratings & 301 Reviews","[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F..."
2,"APPLE iPhone 14 (Midnight, 128 GB)","₹69,999",4.6,"37,021 Ratings & 1,428 Reviews","[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ..."
3,"APPLE iPhone 14 (Purple, 128 GB)","₹69,999",4.6,"37,021 Ratings & 1,428 Reviews","[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ..."
4,"APPLE iPhone 14 (Starlight, 128 GB)","₹69,999",4.6,"37,021 Ratings & 1,428 Reviews","[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ..."
5,"Google Pixel 6a (Charcoal, 128 GB)","₹28,999",4.3,"46,804 Ratings & 5,621 Reviews","[6 GB RAM | 128 GB ROM, 15.6 cm (6.14 inch) Fu..."
6,"Google Pixel 6a (Chalk, 128 GB)","₹28,999",4.3,"46,804 Ratings & 5,621 Reviews","[6 GB RAM | 128 GB ROM, 15.6 cm (6.14 inch) Fu..."
7,"realme GT 2 (Steel Black, 128 GB)","₹23,999",4.3,"9,610 Ratings & 1,131 Reviews","[8 GB RAM | 128 GB ROM, 16.81 cm (6.62 inch) F..."
8,"POCO X5 Pro 5G (Horizon Blue, 256 GB)","₹23,999",4.3,"7,800 Ratings & 821 Reviews","[8 GB RAM | 256 GB ROM, 16.94 cm (6.67 inch) F..."
9,"APPLE iPhone 13 (Green, 128 GB)","₹61,999",4.7,"2,25,513 Ratings & 11,650 Reviews","[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ..."

# Data cleaning and preparation
- Changing data types
- Extracting information and creating new columns

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_name  240 non-null    object
 1   Price         240 non-null    object
 2   Rating        231 non-null    object
 3   No_of_RnR     231 non-null    object
 4   Features      240 non-null    object
 5   PageNo        240 non-null    int64
dtypes: int64(1), object(5)
memory usage: 11.4+ KB

In [61]:
# Converting price and rating to float
df.Rating = df.Rating.astype(float)
# df.Price = df.Price.apply(lambda s : float(s.replace('₹','').replace(',',''))
df.Price = df.Price.str.replace('₹','').str.replace(',','').astype(float)

print(df.Rating.dtype)
print(df.Price.dtype)
df.head()

float64
float64

,Product_name,Price,Rating,No_of_RnR,Features
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"4,509 Ratings & 301 Reviews","[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F..."
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"4,509 Ratings & 301 Reviews","[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F..."
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"37,021 Ratings & 1,428 Reviews","[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ..."
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"37,021 Ratings & 1,428 Reviews","[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ..."
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"37,021 Ratings & 1,428 Reviews","[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ..."

In [62]:
text = '3,346 Ratings & 223 Reviews'
rating_regex = re.compile(r'([\d,\s]+)Ratings')
ratings = rating_regex.findall(text)
int(ratings[0].strip().replace(',',''))

3346

In [63]:
# creating functions to get number of ratings and number of reviews
def get_ratings(text):
    if text is np.nan:
        return 0
    else:
        rating_regex = re.compile(r'([\d,\s]+)Ratings')
        ratings = rating_regex.findall(text)
        ratings = int(ratings[0].strip().replace(',',''))
        return ratings
    
def get_reviews(text):
    if text is np.nan:
        return 0
    else:
        review_regex = re.compile(r'([\d,\s]+)Reviews')
        reviews = review_regex.findall(text)
        reviews = int(reviews[0].strip().replace(',',''))
        return reviews
    
print(get_ratings('3,346 Ratings & 223 Reviews'))
print(get_reviews('3,346 Ratings & 223 Reviews'))

3346
223

In [64]:
# Creating columns No_of_ratings and No_of_reviews
df['No_of_ratings'] = df.No_of_RnR.apply(get_ratings)
df['No_of_reviews'] = df.No_of_RnR.apply(get_reviews)
df.drop('No_of_RnR', axis = 1, inplace = True)

df.head(10)

,Product_name,Price,Rating,Features,No_of_ratings,No_of_reviews
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F...",4509,301
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F...",4509,301
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",37021,1428
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",37021,1428
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",37021,1428
5,"Google Pixel 6a (Charcoal, 128 GB)",28999.0,4.3,"[6 GB RAM | 128 GB ROM, 15.6 cm (6.14 inch) Fu...",46804,5621
6,"Google Pixel 6a (Chalk, 128 GB)",28999.0,4.3,"[6 GB RAM | 128 GB ROM, 15.6 cm (6.14 inch) Fu...",46804,5621
7,"realme GT 2 (Steel Black, 128 GB)",23999.0,4.3,"[8 GB RAM | 128 GB ROM, 16.81 cm (6.62 inch) F...",9610,1131
8,"POCO X5 Pro 5G (Horizon Blue, 256 GB)",23999.0,4.3,"[8 GB RAM | 256 GB ROM, 16.94 cm (6.67 inch) F...",7800,821
9,"APPLE iPhone 13 (Green, 128 GB)",61999.0,4.7,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",225513,11650

In [65]:
# Creating a regex to extract brand
brand_regex = re.compile(r'^\w+')
brand_regex.findall('Apple iphone 14')[0]

'Apple'

In [66]:
# creating a brand column
df['Brand'] = df.Product_name.apply(lambda s : brand_regex.findall(s)[0])
df.head(10)

,Product_name,Price,Rating,Features,No_of_ratings,No_of_reviews,Brand
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F...",4509,301,vivo
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"[8 GB RAM | 128 GB ROM, 16.21 cm (6.38 inch) F...",4509,301,vivo
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",37021,1428,APPLE
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",37021,1428,APPLE
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",37021,1428,APPLE
5,"Google Pixel 6a (Charcoal, 128 GB)",28999.0,4.3,"[6 GB RAM | 128 GB ROM, 15.6 cm (6.14 inch) Fu...",46804,5621,Google
6,"Google Pixel 6a (Chalk, 128 GB)",28999.0,4.3,"[6 GB RAM | 128 GB ROM, 15.6 cm (6.14 inch) Fu...",46804,5621,Google
7,"realme GT 2 (Steel Black, 128 GB)",23999.0,4.3,"[8 GB RAM | 128 GB ROM, 16.81 cm (6.62 inch) F...",9610,1131,realme
8,"POCO X5 Pro 5G (Horizon Blue, 256 GB)",23999.0,4.3,"[8 GB RAM | 256 GB ROM, 16.94 cm (6.67 inch) F...",7800,821,POCO
9,"APPLE iPhone 13 (Green, 128 GB)",61999.0,4.7,"[128 GB ROM, 15.49 cm (6.1 inch) Super Retina ...",225513,11650,APPLE

In [67]:
# Converting features list to string  (to work with regular expressions)
df.Features = df.Features.apply(lambda x : ','.join(x))
df.head(10)

,Product_name,Price,Rating,Features,No_of_ratings,No_of_reviews,Brand
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",4509,301,vivo
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",4509,301,vivo
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",37021,1428,APPLE
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",37021,1428,APPLE
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",37021,1428,APPLE
5,"Google Pixel 6a (Charcoal, 128 GB)",28999.0,4.3,"6 GB RAM | 128 GB ROM,15.6 cm (6.14 inch) Full...",46804,5621,Google
6,"Google Pixel 6a (Chalk, 128 GB)",28999.0,4.3,"6 GB RAM | 128 GB ROM,15.6 cm (6.14 inch) Full...",46804,5621,Google
7,"realme GT 2 (Steel Black, 128 GB)",23999.0,4.3,"8 GB RAM | 128 GB ROM,16.81 cm (6.62 inch) Ful...",9610,1131,realme
8,"POCO X5 Pro 5G (Horizon Blue, 256 GB)",23999.0,4.3,"8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Ful...",7800,821,POCO
9,"APPLE iPhone 13 (Green, 128 GB)",61999.0,4.7,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",225513,11650,APPLE

In [68]:
text = df.Features[0]
processor_regex = re.compile(r'([A-Za-z0-9\s]+)Processor')
processor_regex.findall(text)[0].strip()

'Snapdragon 695'

In [69]:
def get_processor(text):
    processor_regex = re.compile(r'([A-Za-z0-9\s]+)Processor')
    processor = processor_regex.findall(text)
    if len(processor) == 0:
        return np.nan
    else:
        return processor[0].strip()
    
get_processor(text)

'Snapdragon 695'

In [36]:
# Creating a Processor column
df['Processor'] = df.Features.apply(get_processor)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor

In [37]:
# Creating a regular expression to extract RAM
text = df.Features[0]
RAM_regex = re.compile(r'([A-Za-z0-9\s]+)RAM')
RAM_regex.findall(text)[0].strip()

'8 GB'

In [38]:
def get_ram(text):
    regex = re.compile(r'([A-Za-z0-9\s]+)RAM')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_ram(text)

'8 GB'

In [39]:
df['RAM'] = df.Features.apply(get_ram)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN

In [40]:
# Creating a regular expression to extract ROM
text = df.Features[0]
ROM_regex = re.compile(r'([A-Za-z0-9\s]+)ROM')
ROM_regex.findall(text)[0].strip()

'128 GB'

In [41]:
def get_rom(text):
    regex = re.compile(r'([A-Za-z0-9\s]+)ROM')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_rom(text)

'128 GB'

In [42]:

df['ROM'] = df.Features.apply(get_rom)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB

In [43]:
df.Features[0]

'8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Full HD+ Display,64 MP (OIS) + 2MP | 16MP Front Camera,4500 mAh Battery,Snapdragon 695 Processor,1 Year of Device & 6 Months for Inbox Accessories'

In [44]:
# Creating a regular expression to extract Battery
text = df.Features[0]
battery_regex = re.compile(r'[A-Za-z0-9\s]+mAh')
battery_regex.findall(text)[0].strip()

'4500 mAh'

In [45]:
def get_battery(text):
    regex = re.compile(r'[A-Za-z0-9\s]+mAh')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_battery(text)

'4500 mAh'

In [46]:
df['Battery'] = df.Features.apply(get_battery)
df.head(5)

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN

In [47]:
text = df.Features[0]
display_regex = re.compile(r'[0-9\s.]+inch')
display_regex.findall(text)[0].strip()

'6.38 inch'

In [48]:
def get_display(text):
    regex = re.compile(r'[0-9\s.]+inch')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_display(text)

'6.38 inch'

In [49]:
df['Display_Size'] = df.Features.apply(get_display)
df.head()

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery,Display_Size
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch

In [50]:
# Creating a regular expression to extract Camera info
text = df.Features[0]
camera_regex = re.compile(r'[A-Za-z0-9\s\(\)\+\|]+Camera')
camera_regex.findall(text)[0].strip()

'64 MP (OIS) + 2MP | 16MP Front Camera'

In [51]:
def get_camera(text):
    regex = re.compile(r'[A-Za-z0-9\s\(\)\+\|]+Camera')
    result = regex.findall(text)
    if len(result) == 0:
        return np.nan
    else:
        return result[0].strip()
    
get_camera(text)

'64 MP (OIS) + 2MP | 16MP Front Camera'

In [52]:
df['Camera'] = df.Features.apply(get_camera)
df.head()

,Product_name,Price,Rating,Features,PageNo,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery,Display_Size,Camera
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch,64 MP (OIS) + 2MP | 16MP Front Camera
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,"8 GB RAM | 128 GB ROM,16.21 cm (6.38 inch) Ful...",1,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch,64 MP (OIS) + 2MP | 16MP Front Camera
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,"128 GB ROM,15.49 cm (6.1 inch) Super Retina XD...",1,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera

In [53]:
# Removing Features Column
df.drop(['Features', 'PageNo'], axis = 1, inplace = True)
df.head()

,Product_name,Price,Rating,No_of_ratings,No_of_reviews,Brand,Processor,RAM,ROM,Battery,Display_Size,Camera
0,"vivo T2 5G (Velocity Wave, 128 GB)",20999.0,4.4,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch,64 MP (OIS) + 2MP | 16MP Front Camera
1,"vivo T2 5G (Nitro Blaze, 128 GB)",20999.0,4.4,4509,301,vivo,Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch,64 MP (OIS) + 2MP | 16MP Front Camera
2,"APPLE iPhone 14 (Midnight, 128 GB)",69999.0,4.6,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera
3,"APPLE iPhone 14 (Purple, 128 GB)",69999.0,4.6,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera
4,"APPLE iPhone 14 (Starlight, 128 GB)",69999.0,4.6,37021,1428,APPLE,6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera

In [54]:
# rearranging the columns
columns = ['Brand', 'Product_name','Processor', 'RAM', 'ROM', 'Battery', 'Display_Size', 'Camera', 'No_of_ratings', 'No_of_reviews', 'Rating', 'Price']
df = df[columns]
df.head(10)

,Brand,Product_name,Processor,RAM,ROM,Battery,Display_Size,Camera,No_of_ratings,No_of_reviews,Rating,Price
0,vivo,"vivo T2 5G (Velocity Wave, 128 GB)",Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch,64 MP (OIS) + 2MP | 16MP Front Camera,4509,301,4.4,20999.0
1,vivo,"vivo T2 5G (Nitro Blaze, 128 GB)",Snapdragon 695,8 GB,128 GB,4500 mAh,6.38 inch,64 MP (OIS) + 2MP | 16MP Front Camera,4509,301,4.4,20999.0
2,APPLE,"APPLE iPhone 14 (Midnight, 128 GB)",6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera,37021,1428,4.6,69999.0
3,APPLE,"APPLE iPhone 14 (Purple, 128 GB)",6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera,37021,1428,4.6,69999.0
4,APPLE,"APPLE iPhone 14 (Starlight, 128 GB)",6 Core Processor,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera,37021,1428,4.6,69999.0
5,Google,"Google Pixel 6a (Charcoal, 128 GB)",Google Tensor,6 GB,128 GB,4410 mAh,6.14 inch,2MP + 12MP | 8MP Front Camera,46804,5621,4.3,28999.0
6,Google,"Google Pixel 6a (Chalk, 128 GB)",Google Tensor,6 GB,128 GB,4410 mAh,6.14 inch,2MP + 12MP | 8MP Front Camera,46804,5621,4.3,28999.0
7,realme,"realme GT 2 (Steel Black, 128 GB)",Qualcomm Snapdragon 888,8 GB,128 GB,5000 mAh,6.62 inch,50MP + 8MP + 2MP | 16MP Front Camera,9610,1131,4.3,23999.0
8,POCO,"POCO X5 Pro 5G (Horizon Blue, 256 GB)",Qualcomm Snapdragon 778G,8 GB,256 GB,5000 mAh,6.67 inch,108MP + 8MP + 2MP | 16MP Front Camera,7800,821,4.3,23999.0
9,APPLE,"APPLE iPhone 13 (Green, 128 GB)",A15 Bionic Chip,NaN,128 GB,NaN,6.1 inch,12MP + 12MP | 12MP Front Camera,225513,11650,4.7,61999.0

In [55]:
df.to_csv('Flipkart Phones.csv', index = False)