# Pandas
- **Pandas** is a fast, powerful and easy to use open source data analysis and manipulation library.
1. Series
2. DataFrame

In [165]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

# 1. Series

In [166]:
data = [10,20,30,40,50]
s1 = pd.Series(data)
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [167]:
type(s1)

pandas.core.series.Series

In [168]:
s1.values

array([10, 20, 30, 40, 50], dtype=int64)

In [169]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [170]:
s1.dtype

dtype('int64')

In [171]:
list(s1.index)

[0, 1, 2, 3, 4]

In [172]:
s1.index = [101,102,103,104,105]
s1

101    10
102    20
103    30
104    40
105    50
dtype: int64

In [173]:
s1.index = ['A', 'B', 'C', 'D', 'E']
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

In [174]:
s1.index = range(1001,1006)
s1

1001    10
1002    20
1003    30
1004    40
1005    50
dtype: int64

In [175]:
s1.index = [1.5,2.5,3.5,4.5,5.7]
s1

1.5    10
2.5    20
3.5    30
4.5    40
5.7    50
dtype: int64

In [176]:
s1.index = ['A', 'B', 'C', 'D', 'E']
s1

A    10
B    20
C    30
D    40
E    50
dtype: int64

## Accessing data in Series

In [177]:
s1[0]

10

In [178]:
s1[1]

20

In [179]:
s1[-1]

50

In [180]:
s1['A']

10

In [181]:
s1['B']

20

In [182]:
s1['D']

40

In [183]:
s1.iloc[0]                       # By positional indexing

10

In [184]:
s1.iloc[[0,1]]

A    10
B    20
dtype: int64

In [185]:
s1.loc['A']                      # By index that has been provided

10

In [186]:
s1.loc[['A','B']]

A    10
B    20
dtype: int64

## Add, update and Delete operations

In [187]:
s1['F'] = 60
s1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [188]:
s1['D'] = 80
s1

A    10
B    20
C    30
D    80
E    50
F    60
dtype: int64

In [189]:
s1.drop('D', inplace = True)

In [190]:
s1

A    10
B    20
C    30
E    50
F    60
dtype: int64

## Slicing

In [191]:
s1[:]

A    10
B    20
C    30
E    50
F    60
dtype: int64

In [192]:
s1[2:5]

C    30
E    50
F    60
dtype: int64

In [193]:
s1[-1::-1]

F    60
E    50
C    30
B    20
A    10
dtype: int64

In [194]:
s1[::2]

A    10
C    30
F    60
dtype: int64

## Creating Series from Dictionary

In [195]:
data = {'Mohit' : 85,
        'Ankit' : 80,
        'Anjali': 86,
        'Varun' : 81}
s = pd.Series(data)
s

Mohit     85
Ankit     80
Anjali    86
Varun     81
dtype: int64

In [196]:
data = {'Jaipur' : 'Rajasthan',
        'Mumbai' : 'Maharashtra',
        'Kolkata': 'West Bengal',
        'Chandigarh' : 'Punjab',
        'Bengaluru' : 'Karnataka'}
data

{'Jaipur': 'Rajasthan',
 'Mumbai': 'Maharashtra',
 'Kolkata': 'West Bengal',
 'Chandigarh': 'Punjab',
 'Bengaluru': 'Karnataka'}

In [197]:
s2 = pd.Series(data)
s2

Jaipur          Rajasthan
Mumbai        Maharashtra
Kolkata       West Bengal
Chandigarh         Punjab
Bengaluru       Karnataka
dtype: object

In [198]:
s2['Jaipur']

'Rajasthan'

In [199]:
s2.index

Index(['Jaipur', 'Mumbai', 'Kolkata', 'Chandigarh', 'Bengaluru'], dtype='object')

In [200]:
s2.values

array(['Rajasthan', 'Maharashtra', 'West Bengal', 'Punjab', 'Karnataka'],
      dtype=object)

In [201]:
s2[0]

'Rajasthan'

In [202]:
s2.loc['Jaipur']

'Rajasthan'

In [203]:
s2.iloc[0]

'Rajasthan'

In [204]:
s2.name = 'States and Capitals'
s2

Jaipur          Rajasthan
Mumbai        Maharashtra
Kolkata       West Bengal
Chandigarh         Punjab
Bengaluru       Karnataka
Name: States and Capitals, dtype: object

In [205]:
s2.name

'States and Capitals'

In [206]:
s2.index.name = 'Capitals'
s2

Capitals
Jaipur          Rajasthan
Mumbai        Maharashtra
Kolkata       West Bengal
Chandigarh         Punjab
Bengaluru       Karnataka
Name: States and Capitals, dtype: object

In [207]:
print(s2.index)
print(s2.values)
print(s2.dtype)
print(s2.name)
print(s2.index.name)

Index(['Jaipur', 'Mumbai', 'Kolkata', 'Chandigarh', 'Bengaluru'], dtype='object', name='Capitals')
['Rajasthan' 'Maharashtra' 'West Bengal' 'Punjab' 'Karnataka']
object
States and Capitals
Capitals

In [208]:
s2[['Jaipur','Mumbai','Kolkata']]

Capitals
Jaipur       Rajasthan
Mumbai     Maharashtra
Kolkata    West Bengal
Name: States and Capitals, dtype: object

In [209]:
roll_no = [101,102,103,104,105]
result = [88,89,93,85,96]

s3 = pd.Series(data = result, index = roll_no)
s3.name = 'Final Result'
s3.index.name = 'Roll No'
s3

Roll No
101    88
102    89
103    93
104    85
105    96
Name: Final Result, dtype: int64

In [210]:
s2

Capitals
Jaipur          Rajasthan
Mumbai        Maharashtra
Kolkata       West Bengal
Chandigarh         Punjab
Bengaluru       Karnataka
Name: States and Capitals, dtype: object

In [211]:
capitals = ['Jaipur', 'Kolkata', 'Mumbai']
s4 = pd.Series(data = s2, index = capitals)
s4

Jaipur       Rajasthan
Kolkata    West Bengal
Mumbai     Maharashtra
Name: States and Capitals, dtype: object

In [212]:
capitals = ['Jaipur', 'Kolkata', 'Mumbai', 'Delhi','Chennai']
s5 = pd.Series(data = s2, index = capitals)
s5

Jaipur       Rajasthan
Kolkata    West Bengal
Mumbai     Maharashtra
Delhi              NaN
Chennai            NaN
Name: States and Capitals, dtype: object

## Functions

In [213]:
s5.isnull()                               # Check for missing values

Jaipur     False
Kolkata    False
Mumbai     False
Delhi       True
Chennai     True
Name: States and Capitals, dtype: bool

In [214]:
s5.notnull()

Jaipur      True
Kolkata     True
Mumbai      True
Delhi      False
Chennai    False
Name: States and Capitals, dtype: bool

In [215]:
s5.isnull().sum()

2

In [216]:
s5['Bengaluru'] = 'Karnataka'
s5

Jaipur         Rajasthan
Kolkata      West Bengal
Mumbai       Maharashtra
Delhi                NaN
Chennai              NaN
Bengaluru      Karnataka
Name: States and Capitals, dtype: object

In [217]:
s5.head()

Jaipur       Rajasthan
Kolkata    West Bengal
Mumbai     Maharashtra
Delhi              NaN
Chennai            NaN
Name: States and Capitals, dtype: object

In [218]:
s5.head(3)

Jaipur       Rajasthan
Kolkata    West Bengal
Mumbai     Maharashtra
Name: States and Capitals, dtype: object

In [219]:
s5.tail()

Kolkata      West Bengal
Mumbai       Maharashtra
Delhi                NaN
Chennai              NaN
Bengaluru      Karnataka
Name: States and Capitals, dtype: object

In [220]:
s5.tail(3)

Delhi              NaN
Chennai            NaN
Bengaluru    Karnataka
Name: States and Capitals, dtype: object

In [221]:
s5['Pune'] = 'Maharashtra'
s5

Jaipur         Rajasthan
Kolkata      West Bengal
Mumbai       Maharashtra
Delhi                NaN
Chennai              NaN
Bengaluru      Karnataka
Pune         Maharashtra
Name: States and Capitals, dtype: object

In [222]:
s5.index = range(101,108)
s5

101      Rajasthan
102    West Bengal
103    Maharashtra
104            NaN
105            NaN
106      Karnataka
107    Maharashtra
Name: States and Capitals, dtype: object

In [223]:
s5[108] = 'Maharashtra'
s5[109] = 'Maharashtra'
s5

101      Rajasthan
102    West Bengal
103    Maharashtra
104            NaN
105            NaN
106      Karnataka
107    Maharashtra
108    Maharashtra
109    Maharashtra
Name: States and Capitals, dtype: object

In [224]:
s5.duplicated()                                   # Check for duplicate values

101    False
102    False
103    False
104    False
105     True
106    False
107     True
108     True
109     True
Name: States and Capitals, dtype: bool

In [225]:
s5.duplicated().sum()

4

# ==============================================
# DataFrames

In [226]:
employee1 = pd.Series({'Name' : 'Utkarsh', 'ID' : 1, 'Gender' : 'Male', 'Salary':95000})
employee2 = pd.Series({'Name' : 'Kartik', 'ID' : 2, 'Gender' : 'Male','Salary':85000})
employee3 = pd.Series({'Name' : 'Aishwarya', 'ID' : 3, 'Gender' : 'Female','Salary':75000})
employee4 = pd.Series({'Name' : 'Anand', 'ID' : 4, 'Gender' : 'Male','Salary':65000})
employee5 = pd.Series({'Name' : 'Shalini', 'ID' : 5, 'Gender' : 'Female','Salary':90000})
employee6 = pd.Series({'Name' : 'Pratik', 'ID' : 6, 'Gender' : 'Male','Salary':80000})
employee7 = pd.Series({'Name' : 'Monalika', 'ID' : 7, 'Gender' : 'Female','Salary':70000})
employee8 = pd.Series({'Name' : 'Ayesha', 'ID' : 8, 'Gender' : 'Female','Salary':60000})
employee9 = pd.Series({'Name' : 'Anant', 'ID' : 9, 'Gender' : 'Male','Salary':100000})
employee10 = pd.Series({'Name' : 'Shamiksha', 'ID' : 10, 'Gender' : 'Female','Salary':45000})
employee11 = pd.Series({'Name' : 'Prashant', 'ID' : 11, 'Gender' : 'Male','Salary':55000})
employee12 = pd.Series({'Name' : 'Mohini', 'ID' : 12, 'Gender' : 'Female','Salary':65000})

In [227]:
employee1

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
dtype: object

In [228]:
employees = [employee1,employee2,employee3,employee4,employee5,employee6,employee7,employee8,employee9,employee10,employee11,employee12]
df1 = pd.DataFrame(data = employees, index = range(101,113))
df1

          Name  ID  Gender  Salary
101    Utkarsh   1    Male   95000
102     Kartik   2    Male   85000
103  Aishwarya   3  Female   75000
104      Anand   4    Male   65000
105    Shalini   5  Female   90000
106     Pratik   6    Male   80000
107   Monalika   7  Female   70000
108     Ayesha   8  Female   60000
109      Anant   9    Male  100000
110  Shamiksha  10  Female   45000
111   Prashant  11    Male   55000
112     Mohini  12  Female   65000

 - Single and two dimensional data
 - Rows and columns format
 - Tabular data
 - Data Frame
 - Structured data
 - Unstructured data

In [229]:
df1.head()

          Name  ID  Gender  Salary
101    Utkarsh   1    Male   95000
102     Kartik   2    Male   85000
103  Aishwarya   3  Female   75000
104      Anand   4    Male   65000
105    Shalini   5  Female   90000

In [230]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 101 to 112
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    12 non-null     object
 1   ID      12 non-null     int64
 2   Gender  12 non-null     object
 3   Salary  12 non-null     int64
dtypes: int64(2), object(2)
memory usage: 516.0+ bytes

In [231]:
df1.index

RangeIndex(start=101, stop=113, step=1)

In [232]:
df1.values

array([['Utkarsh', 1, 'Male', 95000],
       ['Kartik', 2, 'Male', 85000],
       ['Aishwarya', 3, 'Female', 75000],
       ['Anand', 4, 'Male', 65000],
       ['Shalini', 5, 'Female', 90000],
       ['Pratik', 6, 'Male', 80000],
       ['Monalika', 7, 'Female', 70000],
       ['Ayesha', 8, 'Female', 60000],
       ['Anant', 9, 'Male', 100000],
       ['Shamiksha', 10, 'Female', 45000],
       ['Prashant', 11, 'Male', 55000],
       ['Mohini', 12, 'Female', 65000]], dtype=object)

In [233]:
df1.columns

Index(['Name', 'ID', 'Gender', 'Salary'], dtype='object')

In [234]:
df1.name = 'Employee_Details'
df1.index.name = 'Employee_ID'

In [235]:
df1.name

'Employee_Details'

In [236]:
df1.index.name

'Employee_ID'

## Accessing data from DataFrame

In [237]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

#### Accessing Columns

In [238]:
df1['Name']

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
104        Anand
105      Shalini
106       Pratik
107     Monalika
108       Ayesha
109        Anant
110    Shamiksha
111     Prashant
112       Mohini
Name: Name, dtype: object

In [239]:
df1['Salary']

Employee_ID
101     95000
102     85000
103     75000
104     65000
105     90000
106     80000
107     70000
108     60000
109    100000
110     45000
111     55000
112     65000
Name: Salary, dtype: int64

In [240]:
df1[['Name', 'Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
102             Kartik   85000
103          Aishwarya   75000
104              Anand   65000
105            Shalini   90000
106             Pratik   80000
107           Monalika   70000
108             Ayesha   60000
109              Anant  100000
110          Shamiksha   45000
111           Prashant   55000
112             Mohini   65000

In [241]:
df1.Name

Employee_ID
101      Utkarsh
102       Kartik
103    Aishwarya
104        Anand
105      Shalini
106       Pratik
107     Monalika
108       Ayesha
109        Anant
110    Shamiksha
111     Prashant
112       Mohini
Name: Name, dtype: object

In [242]:
df1.Salary

Employee_ID
101     95000
102     85000
103     75000
104     65000
105     90000
106     80000
107     70000
108     60000
109    100000
110     45000
111     55000
112     65000
Name: Salary, dtype: int64

#### Accessing Records (Rows)

In [243]:
df1.loc[101]

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
Name: 101, dtype: object

In [244]:
df1.iloc[0]

Name      Utkarsh
ID              1
Gender       Male
Salary      95000
Name: 101, dtype: object

In [245]:
df1.loc[105]

Name      Shalini
ID              5
Gender     Female
Salary      90000
Name: 105, dtype: object

In [246]:
df1.loc[[101,105,109]]

                Name  ID  Gender  Salary
Employee_ID
101          Utkarsh   1    Male   95000
105          Shalini   5  Female   90000
109            Anant   9    Male  100000

In [247]:
df1.iloc[[0,4,6,9]]

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
105            Shalini   5  Female   90000
107           Monalika   7  Female   70000
110          Shamiksha  10  Female   45000

### Accessing Specific Values

In [248]:
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000

In [249]:
df1.loc[105]['Salary']

90000

In [250]:
df1.loc[103]['Name']

'Aishwarya'

In [251]:
df1.iloc[4]['Salary']

90000

In [252]:
df1.iloc[2]['Name']

'Aishwarya'

In [253]:
df1['Salary'][105]

90000

In [254]:
df1['Name'][103]

'Aishwarya'

In [255]:
df1.Salary[105]

90000

In [256]:
df1.Name[103]

'Aishwarya'

In [257]:
df1.loc[[101,105,108]]['Salary']

Employee_ID
101    95000
105    90000
108    60000
Name: Salary, dtype: int64

In [258]:
df1.loc[[101,105,108,110]][['Name', 'Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000

In [259]:
df1.iloc[[0,4,7,9]][['Name', 'Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000

In [260]:
df1.loc[105, 'Salary']                              # df1.loc[105]['Salary']

90000

In [261]:
df1.loc[[105,108,110], 'Salary']

Employee_ID
105    90000
108    60000
110    45000
Name: Salary, dtype: int64

In [262]:
df1.loc[[105,108,110, 101], ['Name','Salary']]

                  Name  Salary
Employee_ID
105            Shalini   90000
108             Ayesha   60000
110          Shamiksha   45000
101            Utkarsh   95000

In [263]:
df1.loc[101:106]

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000

In [264]:
df1.loc[101:106, ['Name','Salary']]

                  Name  Salary
Employee_ID
101            Utkarsh   95000
102             Kartik   85000
103          Aishwarya   75000
104              Anand   65000
105            Shalini   90000
106             Pratik   80000

## Adding and Deleting Rows and Columns

In [265]:
df1.loc[113] = ['Priti', 13, 'Female', 71000]
df1

                  Name  ID  Gender  Salary
Employee_ID
101            Utkarsh   1    Male   95000
102             Kartik   2    Male   85000
103          Aishwarya   3  Female   75000
104              Anand   4    Male   65000
105            Shalini   5  Female   90000
106             Pratik   6    Male   80000
107           Monalika   7  Female   70000
108             Ayesha   8  Female   60000
109              Anant   9    Male  100000
110          Shamiksha  10  Female   45000
111           Prashant  11    Male   55000
112             Mohini  12  Female   65000
113              Priti  13  Female   71000

In [266]:
df1['Age'] = np.random.randint(25,50,13)
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   39
102             Kartik   2    Male   85000   28
103          Aishwarya   3  Female   75000   30
104              Anand   4    Male   65000   31
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
107           Monalika   7  Female   70000   40
108             Ayesha   8  Female   60000   33
109              Anant   9    Male  100000   46
110          Shamiksha  10  Female   45000   26
111           Prashant  11    Male   55000   46
112             Mohini  12  Female   65000   31
113              Priti  13  Female   71000   35

In [267]:
df1.drop(113, inplace = True, axis = 0)
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   39
102             Kartik   2    Male   85000   28
103          Aishwarya   3  Female   75000   30
104              Anand   4    Male   65000   31
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
107           Monalika   7  Female   70000   40
108             Ayesha   8  Female   60000   33
109              Anant   9    Male  100000   46
110          Shamiksha  10  Female   45000   26
111           Prashant  11    Male   55000   46
112             Mohini  12  Female   65000   31

In [268]:
df1['City'] = 'Jaipur'
df1

                  Name  ID  Gender  Salary  Age    City
Employee_ID
101            Utkarsh   1    Male   95000   39  Jaipur
102             Kartik   2    Male   85000   28  Jaipur
103          Aishwarya   3  Female   75000   30  Jaipur
104              Anand   4    Male   65000   31  Jaipur
105            Shalini   5  Female   90000   41  Jaipur
106             Pratik   6    Male   80000   38  Jaipur
107           Monalika   7  Female   70000   40  Jaipur
108             Ayesha   8  Female   60000   33  Jaipur
109              Anant   9    Male  100000   46  Jaipur
110          Shamiksha  10  Female   45000   26  Jaipur
111           Prashant  11    Male   55000   46  Jaipur
112             Mohini  12  Female   65000   31  Jaipur

In [269]:
df1.drop('City', inplace = True, axis = 1)
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male   95000   39
102             Kartik   2    Male   85000   28
103          Aishwarya   3  Female   75000   30
104              Anand   4    Male   65000   31
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
107           Monalika   7  Female   70000   40
108             Ayesha   8  Female   60000   33
109              Anant   9    Male  100000   46
110          Shamiksha  10  Female   45000   26
111           Prashant  11    Male   55000   46
112             Mohini  12  Female   65000   31

In [270]:
df1.loc[101, 'Salary'] = 200000
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   39
102             Kartik   2    Male   85000   28
103          Aishwarya   3  Female   75000   30
104              Anand   4    Male   65000   31
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
107           Monalika   7  Female   70000   40
108             Ayesha   8  Female   60000   33
109              Anant   9    Male  100000   46
110          Shamiksha  10  Female   45000   26
111           Prashant  11    Male   55000   46
112             Mohini  12  Female   65000   31

In [271]:
df1.loc[[102,103], 'Salary'] = [90000, 80000]
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   39
102             Kartik   2    Male   90000   28
103          Aishwarya   3  Female   80000   30
104              Anand   4    Male   65000   31
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
107           Monalika   7  Female   70000   40
108             Ayesha   8  Female   60000   33
109              Anant   9    Male  100000   46
110          Shamiksha  10  Female   45000   26
111           Prashant  11    Male   55000   46
112             Mohini  12  Female   65000   31

## Querying Based on Condition

In [272]:
df1[df1.Age > 40]

                 Name  ID  Gender  Salary  Age
Employee_ID
105           Shalini   5  Female   90000   41
109             Anant   9    Male  100000   46
111          Prashant  11    Male   55000   46

In [273]:
df1[df1['Salary'] < 70000]

                  Name  ID  Gender  Salary  Age
Employee_ID
104              Anand   4    Male   65000   31
108             Ayesha   8  Female   60000   33
110          Shamiksha  10  Female   45000   26
111           Prashant  11    Male   55000   46
112             Mohini  12  Female   65000   31

In [274]:
df1[df1.Salary < 70000][['Name', 'Salary']]

                  Name  Salary
Employee_ID
104              Anand   65000
108             Ayesha   60000
110          Shamiksha   45000
111           Prashant   55000
112             Mohini   65000

In [275]:
df1[df1.Gender == 'Male']

                 Name  ID Gender  Salary  Age
Employee_ID
101           Utkarsh   1   Male  200000   39
102            Kartik   2   Male   90000   28
104             Anand   4   Male   65000   31
106            Pratik   6   Male   80000   38
109             Anant   9   Male  100000   46
111          Prashant  11   Male   55000   46

In [276]:
df1[df1.Gender == 'Male'][df1.Salary > 80000]

                Name  ID Gender  Salary  Age
Employee_ID
101          Utkarsh   1   Male  200000   39
102           Kartik   2   Male   90000   28
109            Anant   9   Male  100000   46

In [277]:
df1[df1.Gender == 'Female'][df1.Salary < 100000]

                  Name  ID  Gender  Salary  Age
Employee_ID
103          Aishwarya   3  Female   80000   30
105            Shalini   5  Female   90000   41
107           Monalika   7  Female   70000   40
108             Ayesha   8  Female   60000   33
110          Shamiksha  10  Female   45000   26
112             Mohini  12  Female   65000   31

In [278]:
df1[df1.Gender == 'Male'][df1.Salary > 60000][df1.Salary < 120000]

               Name  ID Gender  Salary  Age
Employee_ID
102          Kartik   2   Male   90000   28
104           Anand   4   Male   65000   31
106          Pratik   6   Male   80000   38
109           Anant   9   Male  100000   46

In [279]:
df1[df1.Gender == 'Female'][df1.Age > 45]

Empty DataFrame
Columns: [Name, ID, Gender, Salary, Age]
Index: []

In [280]:
# Extract name, gender and salary or all male employees having salary between 80000 to 120000
df1[df1.Gender == 'Male'][df1.Salary >= 80000][df1.Salary <= 120000][['Name', 'Gender', 'Salary']]

               Name Gender  Salary
Employee_ID
102          Kartik   Male   90000
106          Pratik   Male   80000
109           Anant   Male  100000

In [281]:
df1.query('Salary > 70000')

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   39
102             Kartik   2    Male   90000   28
103          Aishwarya   3  Female   80000   30
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
109              Anant   9    Male  100000   46

In [282]:
df1.query('Gender == "Male"')

                 Name  ID Gender  Salary  Age
Employee_ID
101           Utkarsh   1   Male  200000   39
102            Kartik   2   Male   90000   28
104             Anand   4   Male   65000   31
106            Pratik   6   Male   80000   38
109             Anant   9   Male  100000   46
111          Prashant  11   Male   55000   46

In [283]:
df1.query('Salary > 70000 and Age > 40')

                Name  ID  Gender  Salary  Age
Employee_ID
105          Shalini   5  Female   90000   41
109            Anant   9    Male  100000   46

In [284]:
df1.query('Salary >= 70000 and Salary <= 90000')

                  Name  ID  Gender  Salary  Age
Employee_ID
102             Kartik   2    Male   90000   28
103          Aishwarya   3  Female   80000   30
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
107           Monalika   7  Female   70000   40

In [285]:
df1.query("Gender == 'Male' and Salary >= 80000 and Salary <= 120000")[['Name', 'Gender', 'Salary']]

               Name Gender  Salary
Employee_ID
102          Kartik   Male   90000
106          Pratik   Male   80000
109           Anant   Male  100000

# Important Functions

In [286]:
df1

                  Name  ID  Gender  Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000   39
102             Kartik   2    Male   90000   28
103          Aishwarya   3  Female   80000   30
104              Anand   4    Male   65000   31
105            Shalini   5  Female   90000   41
106             Pratik   6    Male   80000   38
107           Monalika   7  Female   70000   40
108             Ayesha   8  Female   60000   33
109              Anant   9    Male  100000   46
110          Shamiksha  10  Female   45000   26
111           Prashant  11    Male   55000   46
112             Mohini  12  Female   65000   31

In [287]:
df1.loc[113] = df1.loc[109]
df1.loc[114] = df1.loc[110]
df1.loc[115] = ['Kavita', 15, np.nan, 85000, 30]
df1.loc[116] = ['Pratik', 16, np.nan, np.nan, 32]
df1

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   39
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
105            Shalini   5  Female   90000.0   41
106             Pratik   6    Male   80000.0   38
107           Monalika   7  Female   70000.0   40
108             Ayesha   8  Female   60000.0   33
109              Anant   9    Male  100000.0   46
110          Shamiksha  10  Female   45000.0   26
111           Prashant  11    Male   55000.0   46
112             Mohini  12  Female   65000.0   31
113              Anant   9    Male  100000.0   46
114          Shamiksha  10  Female   45000.0   26
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [288]:
df1.head()

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   39
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
105            Shalini   5  Female   90000.0   41

In [289]:
df1.head(10)

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   39
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
105            Shalini   5  Female   90000.0   41
106             Pratik   6    Male   80000.0   38
107           Monalika   7  Female   70000.0   40
108             Ayesha   8  Female   60000.0   33
109              Anant   9    Male  100000.0   46
110          Shamiksha  10  Female   45000.0   26

In [290]:
df1.tail()

                  Name  ID  Gender    Salary  Age
Employee_ID
112             Mohini  12  Female   65000.0   31
113              Anant   9    Male  100000.0   46
114          Shamiksha  10  Female   45000.0   26
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [291]:
df1.tail(6)

                  Name  ID  Gender    Salary  Age
Employee_ID
111           Prashant  11    Male   55000.0   46
112             Mohini  12  Female   65000.0   31
113              Anant   9    Male  100000.0   46
114          Shamiksha  10  Female   45000.0   26
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [292]:
# Check for null values
df1.isnull().sum()

Name      0
ID        0
Gender    2
Salary    1
Age       0
dtype: int64

In [293]:
df1.isna().sum()

Name      0
ID        0
Gender    2
Salary    1
Age       0
dtype: int64

In [294]:
# Check for duplicates
df1.duplicated().sum()

2

In [295]:
# To drop duplicate records
df1.drop_duplicates(inplace = True)
df1

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   39
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
105            Shalini   5  Female   90000.0   41
106             Pratik   6    Male   80000.0   38
107           Monalika   7  Female   70000.0   40
108             Ayesha   8  Female   60000.0   33
109              Anant   9    Male  100000.0   46
110          Shamiksha  10  Female   45000.0   26
111           Prashant  11    Male   55000.0   46
112             Mohini  12  Female   65000.0   31
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [296]:
df1.nunique()

Name      13
ID        14
Gender     2
Salary    10
Age       11
dtype: int64

In [297]:
df1['Salary'].nunique()

10

In [298]:
df1['Name'].nunique()

13

In [299]:
df1['Name'].unique()

array(['Utkarsh', 'Kartik', 'Aishwarya', 'Anand', 'Shalini', 'Pratik',
       'Monalika', 'Ayesha', 'Anant', 'Shamiksha', 'Prashant', 'Mohini',
       'Kavita'], dtype=object)

In [300]:
df1['Gender'].unique()

array(['Male', 'Female', nan], dtype=object)

In [301]:
df1['Gender'].dropna().unique()

array(['Male', 'Female'], dtype=object)

In [302]:
df1.sort_index()

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   39
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
105            Shalini   5  Female   90000.0   41
106             Pratik   6    Male   80000.0   38
107           Monalika   7  Female   70000.0   40
108             Ayesha   8  Female   60000.0   33
109              Anant   9    Male  100000.0   46
110          Shamiksha  10  Female   45000.0   26
111           Prashant  11    Male   55000.0   46
112             Mohini  12  Female   65000.0   31
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [303]:
df1.sort_index(ascending = False)

                  Name  ID  Gender    Salary  Age
Employee_ID
116             Pratik  16     NaN       NaN   32
115             Kavita  15     NaN   85000.0   30
112             Mohini  12  Female   65000.0   31
111           Prashant  11    Male   55000.0   46
110          Shamiksha  10  Female   45000.0   26
109              Anant   9    Male  100000.0   46
108             Ayesha   8  Female   60000.0   33
107           Monalika   7  Female   70000.0   40
106             Pratik   6    Male   80000.0   38
105            Shalini   5  Female   90000.0   41
104              Anand   4    Male   65000.0   31
103          Aishwarya   3  Female   80000.0   30
102             Kartik   2    Male   90000.0   28
101            Utkarsh   1    Male  200000.0   39

In [304]:
df1.sort_values(by = 'Salary')

                  Name  ID  Gender    Salary  Age
Employee_ID
110          Shamiksha  10  Female   45000.0   26
111           Prashant  11    Male   55000.0   46
108             Ayesha   8  Female   60000.0   33
104              Anand   4    Male   65000.0   31
112             Mohini  12  Female   65000.0   31
107           Monalika   7  Female   70000.0   40
103          Aishwarya   3  Female   80000.0   30
106             Pratik   6    Male   80000.0   38
115             Kavita  15     NaN   85000.0   30
102             Kartik   2    Male   90000.0   28
105            Shalini   5  Female   90000.0   41
109              Anant   9    Male  100000.0   46
101            Utkarsh   1    Male  200000.0   39
116             Pratik  16     NaN       NaN   32

In [305]:
df1.sort_values(by = 'Salary', ascending = False)

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   39
109              Anant   9    Male  100000.0   46
102             Kartik   2    Male   90000.0   28
105            Shalini   5  Female   90000.0   41
115             Kavita  15     NaN   85000.0   30
103          Aishwarya   3  Female   80000.0   30
106             Pratik   6    Male   80000.0   38
107           Monalika   7  Female   70000.0   40
104              Anand   4    Male   65000.0   31
112             Mohini  12  Female   65000.0   31
108             Ayesha   8  Female   60000.0   33
111           Prashant  11    Male   55000.0   46
110          Shamiksha  10  Female   45000.0   26
116             Pratik  16     NaN       NaN   32

In [306]:
df1.sort_values(by = 'Name')

                  Name  ID  Gender    Salary  Age
Employee_ID
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
109              Anant   9    Male  100000.0   46
108             Ayesha   8  Female   60000.0   33
102             Kartik   2    Male   90000.0   28
115             Kavita  15     NaN   85000.0   30
112             Mohini  12  Female   65000.0   31
107           Monalika   7  Female   70000.0   40
111           Prashant  11    Male   55000.0   46
106             Pratik   6    Male   80000.0   38
116             Pratik  16     NaN       NaN   32
105            Shalini   5  Female   90000.0   41
110          Shamiksha  10  Female   45000.0   26
101            Utkarsh   1    Male  200000.0   39

In [307]:
df1.sort_values(by = ['Age', 'Salary'])

                  Name  ID  Gender    Salary  Age
Employee_ID
110          Shamiksha  10  Female   45000.0   26
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
115             Kavita  15     NaN   85000.0   30
104              Anand   4    Male   65000.0   31
112             Mohini  12  Female   65000.0   31
116             Pratik  16     NaN       NaN   32
108             Ayesha   8  Female   60000.0   33
106             Pratik   6    Male   80000.0   38
101            Utkarsh   1    Male  200000.0   39
107           Monalika   7  Female   70000.0   40
105            Shalini   5  Female   90000.0   41
111           Prashant  11    Male   55000.0   46
109              Anant   9    Male  100000.0   46

In [308]:
pd.concat([df1,df1],axis = 0)

                  Name  ID  Gender    Salary  Age
Employee_ID
101            Utkarsh   1    Male  200000.0   39
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
105            Shalini   5  Female   90000.0   41
106             Pratik   6    Male   80000.0   38
107           Monalika   7  Female   70000.0   40
108             Ayesha   8  Female   60000.0   33
109              Anant   9    Male  100000.0   46
110          Shamiksha  10  Female   45000.0   26
111           Prashant  11    Male   55000.0   46
112             Mohini  12  Female   65000.0   31
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32
101            Utkarsh   1    Male  200000.0   39
102             Kartik   2    Male   90000.0   28
103          Aishwarya   3  Female   80000.0   30
104              Anand   4    Male   65000.0   31
105            Shalini   5  Female   90000.0   41
106             Pratik   6    Male   80000.0   38
107           Monalika   7  Female   70000.0   40
108             Ayesha   8  Female   60000.0   33
109              Anant   9    Male  100000.0   46
110          Shamiksha  10  Female   45000.0   26
111           Prashant  11    Male   55000.0   46
112             Mohini  12  Female   65000.0   31
115             Kavita  15     NaN   85000.0   30
116             Pratik  16     NaN       NaN   32

In [185]:
pd.concat([df1,df1], axis = 1)

,Name,ID,Gender,Salary,Age,Name,ID,Gender,Salary,Age
Employee_ID,,,,,,,,,,
101,Utkarsh,1,Male,200000.0,28,Utkarsh,1,Male,200000.0,28
102,Kartik,2,Male,90000.0,31,Kartik,2,Male,90000.0,31
103,Aishwarya,3,Female,80000.0,33,Aishwarya,3,Female,80000.0,33
104,Anand,4,Male,65000.0,48,Anand,4,Male,65000.0,48
105,Shalini,5,Female,90000.0,35,Shalini,5,Female,90000.0,35
106,Pratik,6,Male,80000.0,43,Pratik,6,Male,80000.0,43
107,Monalika,7,Female,70000.0,33,Monalika,7,Female,70000.0,33
108,Ayesha,8,Female,60000.0,37,Ayesha,8,Female,60000.0,37
109,Anant,9,Male,100000.0,41,Anant,9,Male,100000.0,41
110,Shamiksha,10,Female,45000.0,34,Shamiksha,10,Female,45000.0,34
111,Prashant,11,Male,55000.0,28,Prashant,11,Male,55000.0,28
112,Mohini,12,Female,65000.0,47,Mohini,12,Female,65000.0,47
115,Kavita,15,NaN,NaN,30,Kavita,15,NaN,NaN,30
116,Pratik,16,NaN,NaN,32,Pratik,16,NaN,NaN,32

In [309]:
df1.Salary.value_counts()

65000.0     2
80000.0     2
90000.0     2
55000.0     1
200000.0    1
85000.0     1
60000.0     1
45000.0     1
70000.0     1
100000.0    1
Name: Salary, dtype: int64

In [310]:
df1.Gender.value_counts()

Female    6
Male      6
Name: Gender, dtype: int64

In [311]:
df1.Gender.value_counts(normalize = True)

Female    0.5
Male      0.5
Name: Gender, dtype: float64

In [312]:
df1.describe()

              ID         Salary        Age
count  14.000000      13.000000  14.000000
mean    7.785714   83461.538462  35.071429
std     4.660448   38372.332447   6.521730
min     1.000000   45000.000000  26.000000
25%     4.250000   65000.000000  30.250000
50%     7.500000   80000.000000  32.500000
75%    10.750000   90000.000000  39.750000
max    16.000000  200000.000000  46.000000

In [314]:
df1[['Age','Salary']].describe()

             Age         Salary
count  14.000000      13.000000
mean   35.071429   83461.538462
std     6.521730   38372.332447
min    26.000000   45000.000000
25%    30.250000   65000.000000
50%    32.500000   80000.000000
75%    39.750000   90000.000000
max    46.000000  200000.000000

In [315]:
df1.count()

Name      14
ID        14
Gender    12
Salary    13
Age       14
dtype: int64

In [316]:
df1.mean()

ID            7.785714
Salary    83461.538462
Age          35.071429
dtype: float64

In [317]:
df1['Salary'].mean()        # df1.Salary.mean()

83461.53846153847

In [318]:
df1.var()

ID        2.171978e+01
Salary    1.472436e+09
Age       4.253297e+01
dtype: float64

In [319]:
df1.std()

ID            4.660448
Salary    38372.332447
Age           6.521730
dtype: float64

In [320]:
df1.median()

ID            7.5
Salary    80000.0
Age          32.5
dtype: float64

In [321]:
df1['Age'].mode()

0    30
1    31
2    46
dtype: int64

In [322]:
df1.Age.value_counts()

46    2
30    2
31    2
32    1
33    1
38    1
39    1
40    1
41    1
26    1
28    1
Name: Age, dtype: int64

In [323]:
df1.Age.quantile(0.25)

30.25

In [324]:
df1.Age.quantile(0.5)

32.5

In [325]:
df1.Age.quantile(0.75)

39.75

In [326]:
df1['Salary'].apply(np.sqrt)

Employee_ID
101    447.213595
102    300.000000
103    282.842712
104    254.950976
105    300.000000
106    282.842712
107    264.575131
108    244.948974
109    316.227766
110    212.132034
111    234.520788
112    254.950976
115    291.547595
116           NaN
Name: Salary, dtype: float64

In [327]:
df1['Salary'].apply(lambda num : 1.1 * num)

Employee_ID
101    220000.0
102     99000.0
103     88000.0
104     71500.0
105     99000.0
106     88000.0
107     77000.0
108     66000.0
109    110000.0
110     49500.0
111     60500.0
112     71500.0
115     93500.0
116         NaN
Name: Salary, dtype: float64

In [330]:
df1.groupby(by = 'Gender')['Age'].mean()

Gender
Female    33.5
Male      38.0
Name: Age, dtype: float64

In [334]:
df1.groupby(by = 'Gender')['Salary'].mean()

Gender
Female    68333.333333
Male      98333.333333
Name: Salary, dtype: float64

In [335]:
df1.corr()

              ID    Salary       Age
ID      1.000000 -0.504931 -0.057667
Salary -0.504931  1.000000  0.258702
Age    -0.057667  0.258702  1.000000

# -------------------------------------------------------------------------------------
## Dealing With CSV Files

In [8]:
data = pd.read_csv('Automobile_Data.csv')
data.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [10]:
data.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [11]:
data.duplicated().sum()

0

In [12]:
data.replace('?', np.nan, inplace =True)

In [13]:
data.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [14]:
data.nunique()

symboling              6
normalized-losses     51
make                  22
fuel-type              2
aspiration             2
num-of-doors           2
body-style             5
drive-wheels           3
engine-location        2
wheel-base            53
length                75
width                 44
height                49
curb-weight          171
engine-type            7
num-of-cylinders       7
engine-size           44
fuel-system            8
bore                  38
stroke                36
compression-ratio     32
horsepower            59
peak-rpm              23
city-mpg              29
highway-mpg           30
price                186
dtype: int64

In [15]:
print('Fuel Types   : ',data['fuel-type'].unique())
print('Body Styles  : ',data['body-style'].unique())
print('Drive Wheels : ',data['drive-wheels'].unique())
print('Fuel System  : ',data['fuel-system'].unique())
print('Engine Type  : ',data['engine-type'].unique())

Fuel Types   :  ['gas' 'diesel']
Body Styles  :  ['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
Drive Wheels :  ['rwd' 'fwd' '4wd']
Fuel System  :  ['mpfi' '2bbl' 'mfi' '1bbl' 'spfi' '4bbl' 'idi' 'spdi']
Engine Type  :  ['dohc' 'ohcv' 'ohc' 'l' 'rotor' 'ohcf' 'dohcv']

In [16]:
data['city-mpg'].mean()

25.21951219512195

In [17]:
data.groupby(by = 'fuel-type')['city-mpg'].mean()

fuel-type
diesel    30.30000
gas       24.67027
Name: city-mpg, dtype: float64

In [18]:
data['body-style'].value_counts()

sedan          96
hatchback      70
wagon          25
hardtop         8
convertible     6
Name: body-style, dtype: int64

In [19]:
data.groupby(by = 'body-style')['highway-mpg'].mean()

body-style
convertible    26.000000
hardtop        27.250000
hatchback      32.171429
sedan          30.833333
wagon          28.720000
Name: highway-mpg, dtype: float64

In [23]:
data.groupby(by = 'aspiration')['highway-mpg'].mean().sort_values(ascending = False)

aspiration
std      31.571429
turbo    27.027027
Name: highway-mpg, dtype: float64

In [22]:
data.groupby(by = 'aspiration')['city-mpg'].mean().sort_values(ascending = False)

aspiration
std      25.839286
turbo    22.405405
Name: city-mpg, dtype: float64

In [24]:
data.groupby(by = ['body-style','fuel-type'])['city-mpg'].mean()

body-style   fuel-type
convertible  gas          20.500000
hardtop      diesel       22.000000
             gas          21.571429
hatchback    diesel       38.000000
             gas          26.144928
sedan        diesel       31.600000
             gas          24.160494
wagon        diesel       24.000000
             gas          24.045455
Name: city-mpg, dtype: float64

In [25]:
data.groupby(by = ['aspiration','fuel-type'])['city-mpg'].mean()

aspiration  fuel-type
std         diesel       36.857143
            gas          25.360248
turbo       diesel       26.769231
            gas          20.041667
Name: city-mpg, dtype: float64

In [26]:
data.groupby(by = ['fuel-type','aspiration'])['city-mpg'].mean()

fuel-type  aspiration
diesel     std           36.857143
           turbo         26.769231
gas        std           25.360248
           turbo         20.041667
Name: city-mpg, dtype: float64